<?php
$this->headTitle("Tạo đơn bán hàng");
?>
<style>.error{color: red}</style>
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('admin-dashboard')?>">Home</a></li>
    <li><a href="<?=$this->url('sell-admin')?>">Danh sách đơn hàng</a></li>
    <li class="active">Tạo đơn bán hàng</li>
</ul>
<!-- END BREADCRUMB -->

<div class="page-title">
    <h3><span class="fa fa-arrow-circle-o-left"></span> <?=$this->grocery->getGroceryName()?> | Tạo đơn bán hàng</h3>
</div>
<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <?php
            if(count($this->flashMessenger()->getErrorMessages())>0){
                ?>
                <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->getErrorMessages()[0]?>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="form-group">
                        <div>
                            <select class="form-control selectpicker" id="selectPro" data-live-search="true">
                                <?php
                                foreach ($this->productList as $product){
                                    $arrTmp["id"]=$product->getId();
                                    $arrTmp["name"]=$product->getName();
                                    $arrTmp["code"]=$product->getCode();
                                    $arrTmp["note"]=($product->getNoteOrder()?$product->getNoteOrder():'');
                                    $arrTmp["unit_name"]=$product->getUnit()->getName();
                                    $arrTmp["box_unit"]=$product->getBoxUnit();
                                    $arrTmp["inventory"]=$product->getInventory();
                                    $arrTmp["weight"]=$product->getWeight();
                                    $arrTmp["price"]=$product->getUnitPriceAfterSale();
                                    $arrTmp["price_pack"]=$product->getPackPriceAfterSale();
                                    $arrTmp["option"]='unit';
                                    $arrTmp["qty"]=0;
                                    if(is_null($product->getImg()))
                                        $arrTmp["img"]='<img src="/img/icons/no-image-icon.png" width="40px">';
                                    else
                                        $arrTmp["img"]='<img src="'.$product->getImg().'" style="max-width:40; max-height:30px">';

                                    $json = json_encode($arrTmp);

                                    if($product->getInventory()==0)
                                        $class='class="special"';
                                    else
                                        $class='';
                                    echo '<option '.$class.' value="'.$product->getId().'" data=\''.$json.'\'>'.$product->getCode().' | '.$product->getName(). " - ".$product->getWeight().' | Tồn: '.$product->getInventory().'</option>';
                                }
                                ?>
                            </select>
                        </div>
                        <div>
                            <ul id="productList" class="list-group"></ul>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-9 col-md-offset-3">
                            <input type="submit" disabled name="btnSubmit"  id="btnSubmit" class="btn btn-success" value="Tạo đơn hàng">
                            <span class="pull-right price" id="total-price"></span>
                            <span class="pull-right price" id="total-price-lable"></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-heading ui-draggable-handle">
                    <h3 class="panel-title">Thông tin khách hàng</h3>
                </div>
                <div class="panel-body grocery-info">
                    <div>
                        <div>
                            <label>Tên cửa hàng: </label> <a href="<?=$this->url('grocery-admin',['action'=>'edit','id'=>$this->grocery->getId()])?>"><?=$this->grocery->getGroceryName()?></a>
                            <small class="label label-info"><?=($this->grocery->getActive()==1?'Active':'No Active')?></small>
                        </div>
                        <div><label>Chủ cửa hàng: </label> <?=$this->grocery->getOwnerName()?> </div>
                        <div><label>Điện thoại: </label> <?=$this->grocery->getMobile()?></div>
                        <div><label>Địa chỉ: </label> <a target="_blank" href="https://www.google.com/maps/dir/?api=1&destination=<?=$this->grocery->getLat().','.$this->grocery->getLng()?>"><?=$this->grocery->getAddress()?></a></div>
                        <div>
                            <label>Tuyến: </label>
                            <a href="<?=$this->url('grocery-admin',['action'=>'cat-detail','id'=>$this->grocery->getGroceryCat()->getId()])?>"><?=$this->grocery->getGroceryCat()->getName()?></a>
                        </div>
                        <div><label>Nhân viên: </label> <?=$this->grocery->getGroceryCat()->getUser()->getFullname()?></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<link rel="stylesheet" href="/css/bootstrap-select.min.css">
<script src="/js/bootstrap-select.min.js"></script>
<link rel="stylesheet" href="/css/ajax-bootstrap-select.css">
<script src="/js/ajax-bootstrap-select.js"></script>

<script type='text/javascript' src='/joli/js/plugins/icheck/icheck.min.js'></script>
<style>
    .special {
        color: #fff !important;
        background: #bc0000 !important;
    }
    .warning-color{color: red}
    .list-group-item .title{font-weight: bold}
    .list-group .list-group-item:last-child{
        border-bottom: 1px solid #E5E5E5;
    }
    .price{color: #26a9d1; font-weight: bold; padding-left: 10px}

</style>
<script>
    var myProSelect=[];
    // var hash = location.hash.substring(1);

    $("#selectPro").on("changed.bs.select",
        function(e, clickedIndex, newValue, oldValue) {
            var data = $(this).find(':selected').attr('data');
            var obj = jQuery.parseJSON(data);
            var msg='',cls='',defaultQuantity=1;

            obj.qty=defaultQuantity;

            var html='<li id="li'+obj.id+'" href="#" class="list-group-item list-group-item-action flex-column align-items-start">';
                html+='<div class="d-flex w-100 justify-content-between">';
                html+='<h5 class="mb-1 title">';
                html+=obj.name +'|'+obj.weight;
                html+='<span class="fa fa-times pull-right" onclick="removeProduct('+obj.id+')"></span>';
                html+='</h5>';
                html+='</div>';
                html+='<table style="width: 100%">';
                html+='<tr>';
                html+='<td style="padding-right: 5px; width: 40px">'+obj.img+'</td>';
                html+='<td>';
                html+='<div><span class="'+cls+'">Tồn kho: '+obj.inventory+' '+obj.unit_name+' </span>| Quy cách: '+ obj.box_unit+'</div>';
                html+='<table>';
                html+='     <tr>';
                html+='         <td nowrap="">Giá lẻ:</td>';
                html+='         <td style="padding-left: 10px; font-weight: bold; width: 100%" nowrap="">'+formatCurrency(obj.price.toString())+'</td>';
                html+='     </tr><tr>';
                html+='         <td nowrap="">Giá thùng:</td>';
                html+='         <td style="padding-left: 10px; font-weight: bold;" nowrap="">'+formatCurrency(obj.price_pack.toString())+'</td>';
                html+='     </tr><tr>';
                html+='         <td nowrap="">Đơn vị mua</td>';
                html+='         <td style="padding-left: 10px">';
                html+='             <label class="check"><input type="radio" value="unit" dataId="'+obj.id+'" class="iradio" name="opt'+obj.id+'" checked="checked"/> Theo '+obj.unit_name+'</label>';
                html+='             <label class="check"><input type="radio" value="pack" dataId="'+obj.id+'" class="iradio" name="opt'+obj.id+'"/> Theo thùng</label>';
                html+='         </td>';
                html+='     </tr><tr>';
                html+='         <td nowrap="">Số lượng:</td>';
                html+='         <td style="padding-left: 10px">';
                html+='             <input style="width: 100px" id="qty'+obj.id+'" name="quantity" type="number" onchange="qtyOnchange('+obj.id+')"  value="'+defaultQuantity+'" min="1" class="form-control">';
                html+='         </td>';
                html+='     </tr>';
                html+='</table>';
                html+='<small style="color: #f56b0a">'+obj.note+'</small> <small id="msg'+obj.id+'" class="warning-color">'+msg+'</small>';
                html+='</td></tr></table>';
                html+='</li>';

            var alreadyLi=0;
            $.each( myProSelect, function( key, data ) {
                if(data.id==obj.id) {
                    alreadyLi=1;
                }
            });
            if(alreadyLi==1){
                var liItem =$('#li'+obj.id);
                $('#li'+obj.id).remove();
                $('#productList').prepend(liItem);
            }else{
                $('#productList').prepend(html);
                $('.iradio').iCheck({radioClass: 'iradio_minimal-grey'}).on('ifChecked', function(e) {
                    let option = e.target.value;
                    let id = $(this).attr('dataId');
                    $.each( myProSelect, function( key, data ) {
                        if(data.id==id){
                            $.extend(data,{
                                option:option
                            });
                        }
                    });
                    showInforOrder();
                });
                myProSelect.push(obj);
            }
            $('#qty'+obj.id).focus();

            showInforOrder();
            showButtonSubmitOrder();
        });

    function removeProduct(id){
        $('#li'+id).remove();
        myProSelect = $.grep(myProSelect, function(e){
            return e.id != id;
        });
        showInforOrder();
        showButtonSubmitOrder();
    }

    function showButtonSubmitOrder(){
        if(myProSelect.length > 0)
            $('#btnSubmit').prop('disabled', false);
        else
            $('#btnSubmit').prop('disabled', true);
    }

    function showInforOrder(){
        var totalPrice=0;

        if(myProSelect.length==0){
            $('#total-price').html('');
            $('#total-price-lable').html('');
            return;
        }

        let price;
        let quantity;
        $.each( myProSelect, function( key, data ) {
            quantity=data.qty
            if(data.option=='unit') {
                price = data.price;
                totalPrice += price * quantity;
            }else{
                price=data.price_pack;
                totalPrice+=price*quantity;
            }
        });

        $('#total-price').html(formatCurrency(totalPrice.toString())+" đ");
        $('#total-price-lable').html('Tổng tiền tạm tính:');
    }

    function qtyOnchange(id){
        var obj=$('#qty'+id);
        var value=obj.val();
        if(!value) value=0;

        if(value<0){
            $('#msg'+id).html('Không thể nhập số âm!');
            return;
        }else{
            $('#msg'+id).html('');
        }

        $.each( myProSelect, function( key, data ) {
            if(data.id==id){
                $.extend(data,{
                    qty:parseInt(value)
                });
            }
        });

        showInforOrder();
    }

    $('#btnSubmit').click(function(){
        if(!myProSelect.length){
            alert("Vui lòng chọn sản phẩm.");
            return;
        }
        var err=0;
        $.each( myProSelect, function( key, data ) {
            if(!data.qty){
                alert("Vui lòng nhập số lượng bán sản phẩm "+data.name);
                err=1;
                return;
            };
        });

        if(err==1) return;
        // console.log(myProSelect);
        let jsonObj = [];
        $.each( myProSelect, function( key, data ) {
            let item = {};
            item["id"]=data.id;
            item["option"]=data.option;
            item["qty"]=data.qty;
            jsonObj.push(item);
        });
        // console.log(jsonObj);
        // return;
        run_waitMe();

        //var url = "<?//=$this->url('sell-admin',['action'=>'add','id'=>$this->grocery->getId()])?>//";
        var url = "<?=$this->url('sell-user',['action'=>'add-draft-order','id'=>$this->grocery->getId()])?>";
        $.ajax({
            headers: {Accept: "application/json; charset=utf-8"},
            method: "POST",
            url: url,
            data: {pro:jsonObj}
        }).done(function (data) {
            if(data.status){
                window.location.href = '<?=$this->url('sell-admin',['action'=>'draft'])?>';
            }
            else{
                alert(data.msg);
                stop_waitMe();
            }
        })
    });

    function formatCurrency(value){
        var result=0;
        if (value && value.length >3){
            var numFormat = new Intl.NumberFormat("en-US");
            result= numFormat.format(value.replaceAll( ",","" ));
        }else{
            result= value;
        }
        return result;
    }
</script>