<?php

use Sulde\Service\Common\Common;
use Zend\Mvc\Plugin\FlashMessenger\FlashMessenger;

$title = "Danh sách đơn hàng";
$this->headTitle($title);
?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('admin-dashboard')?>">Home</a></li>
    <li class="active">Danh sách đơn hàng</li>
</ul>
<!-- END BREADCRUMB -->
<div class="page-title">
    <h3><span class="fa fa-arrow-circle-o-left"></span> Đơn hàng chờ đóng gói</h3>
</div>

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <?php
            if($this->flashMessenger()->render(FlashMessenger::NAMESPACE_SUCCESS)){
                ?>
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->render(FlashMessenger::NAMESPACE_SUCCESS)?>
                </div>
                <?php
            }
            if($this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR)){
                ?>
                <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR)?>
                </div>
                <?php
            }
            ?>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <!-- START JUSTIFIED TABS -->
            <div class="panel panel-default tabs">
                <ul class="nav nav-tabs nav-justified">
                    <li>
                        <a href="<?=$this->url('sell-admin',['action'=>'draft'])?>">
                            Chờ xử lý
                            <div style="right: 5px; top: 10px; position: absolute; background-color: #e01e4b; padding: 0 4px; font-size: 14px; -webkit-border-radius:5px; color: white" id="draft_order_number"></div>
                        </a>
                    </li>
                    <li>
                        <a href="<?=$this->url('sell-admin',['action'=>'customer'])?>">
                            Khách tạo
                            <div style="right: 5px; top: 10px; position: absolute; background-color: #e01e4b; padding: 0 4px; font-size: 14px; -webkit-border-radius:5px; color: white" id="cus_order_number"></div>
                        </a>
                    </li>
                    <li class="active">
                        <a href="#tab8" data-toggle="tab">
                            Chờ đóng gói
                            <div style="right: 5px; top: 10px; position: absolute; background-color: #e01e4b; padding: 0 4px; font-size: 14px; -webkit-border-radius:5px; color: white" id="new_order_number"></div>
                        </a>
                    </li>
                    <li><a href="<?=$this->url('sell-admin',['action'=>'packing'])?>">Đang đóng gói</a></li>
                    <li><a href="<?=$this->url('sell-admin',['action'=>'packed'])?>">Đã đóng gói</a></li>
                    <li><a href="<?=$this->url('sell-admin',['action'=>'delivering'])?>">Đang giao</a></li>
                    <li><a href="<?=$this->url('sell-admin',['action'=>'delivered'])?>">Đã giao</a></li>
                    <li><a href="<?=$this->url('sell-admin',['action'=>'wait-for-pay'])?>">Chưa thanh toán</a></li>
                    <li><a href="<?=$this->url('sell-admin',['action'=>'paid-order'])?>">Hoàn thành</a></li>
                </ul>
                <div class="panel-body tab-content">
                    <div class="tab-pane active" id="tab8">
                        <?php
                        if(count($this->listGroceryMerge)>0){
                            ?>
                            <div class="alert alert-info" role="alert">
                                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                                <strong>Các đơn cần gộp:</strong>
                                <?php
                                foreach ($this->listGroceryMerge as $key=>$item)
                                    echo '<a style="color:#ffffff" href="' .$this->url('sell-admin',['action'=>'merge-sell-order','id'=>$key]).'?s=1">'.$item['name'].' ('.$item['order-number'].' đơn)</a>, ';
                                ?>
                            </div>
                            <?php
                        }
                        ?>
                        <table class="table nowrap table-hover display" style="width:100%" id="tblOrder">
                            <thead>
                            <tr>
                                <th><input type="checkbox" id="selectAll" value="0" /></th>
                                <th>STT</th>
                                <th>Mã đơn</th>
                                <th>Khách hàng</th>
                                <th>Ngày tạo</th>
                                <th>Người tạo</th>
                                <th>Xe giao</th>
                                <th>Tổng đơn</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php
                            $i=1;
                            foreach ($this->sellOrder as $order){
                                $odn=$order->getOrderCode();

//                                $method = ($order->getMethod()>0?'<span class="fa fa-phone-square"></span> Admin':$order->getUser()->getFullname());
                                if($order->getMethod()>0)
                                    $method='<span class="fa fa-phone-square"></span> Admin';
                                else if($order->getMethod()==-1)
                                    $method='<span class="glyphicon glyphicon-user"></span> Customer';
                                else
                                    $method=$order->getUser()->getFullname();

                                $title='';
                                $popover='';
                                if($order->getNote()){
                                    $noteArr =explode("\n",$order->getNote());
                                    if(count($noteArr)){
                                        foreach ($noteArr as $value){
                                            $arrNote = explode("|",$value);
                                            $title.=@$arrNote[2];
                                        }
                                    }
                                    $popover='<span class="fa fa-bell" data-toggle="tooltip" data-placement="top" title="" data-original-title="'.$title.'"></span>';
                                }
                                $deliveryCar=($order->getDeliveryCar()?$order->getDeliveryCar().'-'.$order->getDeliveryCarTime():'');
                                echo '<tr>';
                                echo '<td><input type="checkbox" value="'.$order->getId().'"/></td>';
                                echo '<td>'.$i++.'</td>';
                                echo '<td>'.$odn.'</td>';
                                echo '<td nowrap=""><a href="'.$this->url('sell-admin',['action'=>'detail-order','id'=>$order->getId()]).'"><b>'.$order->getGrocery()->getGroceryName().'</b> '.$popover.'<br><i>('.Common::substrwords($order->getGrocery()->getAddress(),40).')</i></a></td>';
                                echo '<td>'.Common::formatDateTime($order->getCreatedDate()).'</td>';
                                echo '<td nowrap="">'.$method.'</td>';
                                echo '<td nowrap="">'.$deliveryCar.'</td>';
                                echo '<td>'.Common::formatMoney(round($order->getTotalAmountToPaid()/1000)*1000).'</td>';
                                echo '<td class="text-right">';

                                echo '<a href="'.$this->url('sell-admin',['action'=>'print','id'=>$order->getId()]).'?s=11" class="btn btn-info"><span class="fa fa-print"> In & Chuyển đóng gói</span></a>';
//                                echo '<button id="btnDeliveryConfirm" onclick="showModalDeliveryConfirm('.$order->getId().')" type="button" class="btn btn-primary"><span class="fa fa-truck"> Giao hàng</span></button>';
//                                echo '<a href="'.$this->url('sell-admin',['action'=>'return','id'=>$order->getId()]).'" class="btn btn-warning"><span class="fa fa-warning"> Trả hàng</span></a>';
//                                echo '<button id="btnPayConfirm" onclick="showModalPayConfirm('.$order->getId().')" type="button" class="btn btn-success"><span class="fa fa-credit-card"> Thanh toán</span></button>';
                                echo '<a href="'.$this->url('sell-admin',['action'=>'edit-order','id'=>$order->getId()]).'" class="btn btn-warning"><span class="fa fa-edit"> Sửa đơn</span></a> ';
                                ?>
                                <ul class="panel-controls">
                                    <li class="dropdown">
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="fa fa-cog"></span></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="<?=$this->url('sell-admin',['action'=>'edit-order','id'=>$order->getId()])?>"><span class="fa fa-edit"></span> Sửa đơn</a></li>
                                            <li><a href="<?=$this->url('sell-admin',['action'=>'return','id'=>$order->getId()])?>"><span class="fa fa-warning"></span> Trả hàng</a></li>
                                            <li><a style="cursor: pointer" id="btnCancelConfirm" onclick="showModalCancelConfirm('<?=$this->url('sell-admin',['action'=>'cancel-order','id'=>$order->getId()])?>','<?=$order->getGrocery()->getGroceryName()?>')"><span class="fa fa-trash-o"></span> Huỷ đơn</a></li>
                                            <li><a style="cursor: pointer" id="btnPayConfirm" onclick="showModalPayConfirm(<?=$order->getId()?>,'<?=$order->getGrocery()->getGroceryName()?>')"><span class="fa fa-credit-card"></span> Thanh toán</a></li>
                                            <li><a href="<?=$this->url('sell-admin',['action'=>'print','id'=>$order->getId()])?>"><span class="fa fa-print"></span> In đơn</a></li>
                                            <li><a style="cursor: pointer" id="btnDeliveryConfirm" onclick="showModalDeliveryConfirm(<?=$order->getId()?>)"><span class="fa fa-truck"></span> Giao hàng</a></li>
                                        </ul>
                                    </li>
                                </ul>
                                <?php
                                echo '</td>';
                                echo '</tr>';
                            }
                            ?>
                            </tbody>
                            <tfoot>
                            <tr>
                                <th colspan="7" style="text-align:right">Tổng cộng:</th>
                                <th colspan="2"></th>
                            </tr>
                            </tfoot>
                        </table>
                        <button type="button" class="btn btn-info" id="btnPrintOrderChecked">Sắp hàng theo đơn đã chọn</button>
                    </div>
                </div>
            </div>
            <!-- END JUSTIFIED TABS -->
        </div>
    </div>
</div>
<div class="modal fade" id="modalPayConfirm" tabindex="-1" role="dialog" aria-labelledby="modalPayConfirmLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <form id="pay-form" action="<?=$this->url('sell-admin',['action'=>'paid-order'])?>" method="post" name="delivery-form" class="form-horizontal">
            <input type="hidden" name="oid" id="oid">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="modalPayConfirmLabel">Xác nhận thanh toán</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class='col-md-12 padding-bottom-5'>
                            <label class="check"><input type="radio" class="iradio" name="payMethod" value="1" checked="checked"/>Hoàn thành</label>
                            <label class="check"><input type="radio" class="iradio" name="payMethod" value="2"/>Chưa thanh toán hoặc Thanh toán một phần</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class='col-md-12 padding-bottom-5'>
                            <textarea type="text" class="form-control" id="note" name="note" placeholder="Ghi chú" rows="3"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Xác nhận</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="modalDeliveryConfirm" tabindex="-1" role="dialog" aria-labelledby="modalDeliveryConfirmLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <form id="delivery-form" action="<?=$this->url('sell-admin',['action'=>'delivery'])?>" method="post" name="delivery-form" class="form-horizontal">
            <input type="hidden" name="oid" id="oidDelivery">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="modalDeliveryConfirmLabel">Ghi chú cho shipper</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class='col-md-12 padding-bottom-5'>
                            <textarea type="text" class="form-control" id="note" name="note" placeholder="Ghi chú" rows="3"></textarea>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-success">Chuyển shipper</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="modal fade" id="modalCancelConfirm" tabindex="-1" role="dialog" aria-labelledby="modalCancelConfirmLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
            <input type="hidden" id="cancelUrl">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="modalCancelConfirmLabel">Xác nhận huỷ đơn hàng</h4>
                </div>
                <div class="modal-body">
                    Sau khi xác nhận huỷ, toàn bộ sản phẩm trong đơn hàng được trả lại vào kho. Hành động này không thể khôi phục lại. Bạn chắc chắn muốn huỷ?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button onclick="btnConfirmCancel()" class="btn btn-success">Xác nhận</button>
                </div>
            </div>
    </div>
</div>

<style>
    .panel-body table td{vertical-align: center !important;}

    .dataTables_length{
        float: right;
        width: auto;
    }
    .dataTables_filter{
        float: left;
    }
    .dataTables_filter label{
        float: unset;
    }
    .dataTables_filter label input{width: 250px}
    .panel-body table tr td{
        vertical-align: middle;
    }
</style>
<script type="text/javascript" src="/joli/js/plugins/datatables/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="/joli/js/plugins/icheck/icheck.min.js"></script>

<script>
    $(document).ready(function () {
        $('#tblOrder').DataTable({
            paging: false,
            pageLength:50,
            ordering: false,
            info: false,
            // order: [[ 1, "desc" ]],
            // scrollX: true,
            language: {
                searchPlaceholder: ""
            },
            initComplete: function () {
                $('.dataTables_filter label input').focus();
            },
            footerCallback: function (row, data, start, end, display) {
                var api = this.api();

                // Remove the formatting to get integer data for summation
                var intVal = function (i) {
                    return typeof i === 'string' ? i.replace(/[\$,]/g, '') * 1 : typeof i === 'number' ? i : 0;
                };

                // Total over all pages
                // total = api
                //     .column(5)
                //     .data()
                //     .reduce(function (a, b) {
                //         return intVal(a) + intVal(b);
                //     }, 0);

                // Total over this page
                pageTotal = api
                    .column(7, { page: 'current' })
                    .data()
                    .reduce(function (a, b) {
                        return intVal(a) + intVal(b);
                    }, 0);

                // Update footer
                $(api.column(7).footer()).html(formatCurrency(pageTotal.toString())+' đ');
            }
        });

        $('#selectAll').click(function (e) {
            $(this).closest('table').find('td input:checkbox').prop('checked', this.checked);
            // alert('dd');
        });

        $('#btnPrintOrderChecked').click(function(){
            var selected = new Array();
            $('#tblOrder input[type="checkbox"]:checked').each(function() {
                var val=$(this).val();
                if(val>0) selected.push(val);
            });

            if(selected.length==0){
                noty({text: 'Chọn 1 hoặc nhiều đơn cần sắp hàng!', layout: 'topRight', type: 'warning',timeout: 4000});
                return;
            }

            let text = 'Nếu bạn nhấn OK thì '+selected.length + " đơn hàng bạn chọn sẽ được chuyển trạng thái đang đóng gói!";
            if (confirm(text) == true) {
                // arrSelectedStr = JSON.stringify(selected);
                let arrSelectedStr = encodeURIComponent(JSON.stringify(selected));
                // console.log(arrSelectedStr)
                let url = '<?=$this->url('sell-admin',['action'=>'print-selected-order','id'=>0])?>';
                url = url + '?s='+ arrSelectedStr;
                window.location.href =  url;
                // console.log(decodeURIComponent(url));
            } else {
                return;
            }
        });

        showNotifyOrderCustomerAndNew();
    });

    function showModalPayConfirm(oId,groceryName){
        $('#oid').val(oId);
        $('#modalPayConfirmLabel').html('Xác nhận thanh toán đơn hàng <b>'+groceryName+'</b>');
        $('#modalPayConfirm').modal({
            keyboard: false,
            backdrop:'static',
            show:true
        });
    }

    function showModalCancelConfirm(url,groceryName){
        $('#cancelUrl').val(url);
        $('#modalCancelConfirmLabel').html('Xác nhận huỷ đơn hàng: '+groceryName);

        $('#modalCancelConfirm').modal({
            keyboard: false,
            backdrop:'static',
            show:true
        });
    }

    function btnConfirmCancel(){
        run_waitMe();
        var url=$('#cancelUrl').val();
        $.ajax({
            headers: {Accept: "application/json; charset=utf-8"},
            method: "POST",
            url: url
        }).done(function(res) {
            alert(res.msg);
            if(res.status==1){
                location.reload();
            }
            stop_waitMe();
        });
    }

    function showModalDeliveryConfirm(oId){
        $('#oidDelivery').val(oId);
        $('#modalDeliveryConfirm').modal({
            keyboard: false,
            backdrop:'static',
            show:true
        });
    }
</script>