<link rel="stylesheet" type="text/css" id="theme" href="/css/sidebar.css"/>
<div class="overlay"></div>
<div class="wrapper">
    <!-- Sidebar  -->
    <nav id="sidebar">
        <div class="sidebar-header">
            <a href="/"><img src="/img/logo.png" width="70px"></a>
        </div>
        <?php
        if($userInfo){
        $fullname = $userInfo->getFullname();
        $name = substr(strrchr($fullname , ' '), 1). '! ';
        $email = $userInfo->getEmail();
        if(!$email) $email='-/-';
        ?>
        <div class="panel panel-default">
            <div class="panel-body profile">
                <div class="profile-image">
                    <img src="/img/users/avatar.png" alt="<?=$fullname?>">
                </div>
                <div class="profile-data">
                    <div class="profile-data-name"><?=$fullname?></div>
                    <div class="profile-data-title"><?=$userInfo->getMobile()?></div>
                </div>
                <div class="profile-controls">
                    <a href="<?=$this->url('user-front',['action'=>'profile'])?>" class="profile-control-left"><span class="fa fa-info"></span></a>
                    <a href="#" class="profile-control-right"><span class="fa fa-phone"></span></a>
                </div>
            </div>
            <div class="panel-body">

                <ul class="list-unstyled components">
                    <li><a href="<?=$this->url('user-front',['action'=>'profile'])?>"><i class="fa fa-user padding-right-10"></i> <span>Thông tin thành viên</span></a></li>
                    <li><a href="<?=$this->url('user-dashboard')?>"><i class="fa fa-desktop padding-right-10"></i><span>Dashboard</span></a></li>
                </ul>
            </div>
        </div>
        <?php }else{ ?>
            <ul class="list-unstyled components">
                <li>
                    <a href="<?=$this->url('user-login')?>"><i class="fa fa-users padding-right-10"></i> <?=$this->translate('Sign up')?></a>
                </li>
                <li>
                    <a href="<?=$this->url('user-login')?>" ><i class="fa fa-user padding-right-10"></i> <?=$this->translate('Sign in')?></a>
                </li>
            </ul>

            <?php
            }
        ?>
    </nav>
</div>