<?php
$title = "User list";
$this->headTitle($title);

use Zend\Mvc\Plugin\FlashMessenger\FlashMessenger; ?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('admin-dashboard')?>">Home</a></li>
    <li class="active">User list</li>
</ul>
<!-- END BREADCRUMB -->

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form action="<?=$this->url('user-admin')?>" role="form" onsubmit="return validateForm();" method="GET" name="hotel-search-form" class="form-horizontal" id="hotel-search-form">
                        <div class="col-md-2">
                            <input type="text" class="form-control" name="mobile" id="user_mobile" value="<?=$searchFormData["mobile"]?>" placeholder="Fill mobile please">
                        </div>
                        <div class="col-md-3">
                            <input type="text" class="form-control xn-search" name="name" id="user_name" value="<?=$searchFormData["name"]?>" placeholder="Fill fullname please">
                        </div>
                        <div class="col-md-2">
                            <input type="text" class="form-control" name="email" id="user_email" value="<?=$searchFormData["email"]?>" placeholder="Fill email please">
                        </div>
                        <div class="col-md-4">
                            <input type="checkbox" name="status" id="user_status"  class="icheckbox" <?php if($searchFormData["status"]==1) echo 'checked="checked"';?> > Actived
                        </div>
                        <div class="col-md-1">
                            <button id="btnSearch" class="btn btn-info"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php
            if($this->flashMessenger()->render(FlashMessenger::NAMESPACE_SUCCESS)){
                ?>
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->render(FlashMessenger::NAMESPACE_SUCCESS)?>
                </div>
                <?php
            }
            if($this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR)){
                ?>
                <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR)?>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
            <div class="panel-body">
                <table class="table table-hover">
                    <thead>
                    <th>STT</th>
                    <th>Mobile</th>
                    <th>Fullname</th>
                    <th>Email</th>
                    <th>Last login</th>
                    <th>Status</th>
                    <th>Option</th>
                    </thead>
                    <tbody>
                    <?php if (count($this->paginator)): ?>
                    <?php
                    $stt = 1;
                    foreach($paginator as $user):?>

                        <tr>
                            <td><?=$stt?></td>
                            <td><?=$this->escapeHtml($user->getMobile())?></td>
                            <td><?=$this->escapeHtml($user->getFullname())?></td>
                            <td><?=$this->escapeHtml($user->getEmail())?></td>
                            <td><?php
                                if($user->getLoginDate()) echo $user->getLoginDate()->format('d/M/Y');
                                else echo "--";
                                ?>
                            </td>
                            <td>
                                <?php
                                if($user->getStatus()==0) echo "Inactive";
                                else echo "Active";
                                ?>
                            <td>

                                <a href="<?=$this->url('user-admin',['action'=>'edit','id'=>$this->escapeHtml($user->getId())])?>">Edit</a> |
                                <a href="<?=$this->url('user-admin',['action'=>'delete','id'=>$this->escapeHtml($user->getId())])?>">Delete</a> |
                                <a href="<?=$this->url('user-admin',['action'=>'change-password','id'=>$this->escapeHtml($user->getId())])?>">Đổi mật khẩu</a>
                            </td>
                        </tr>


                        <?php
                        $stt++;
                    endforeach
                    ?>
                    <?php endif; ?>

                    </tbody>
                </table>
            </div>
            <div class="panel-footer">
                <h3 class="panel-title"><?='<b>'.$paginator->getTotalItemCount().'</b> records'?></h3>
                <?= $this->paginationControl(
                    $this->paginator,
                    'Sliding',
                    'paginator',
                    array('route' => 'user-admin', 'query'=>$this->queryParam)
                ) ?>
            </div>
        </div>
        </div>
    </div>
</div>

<script type='text/javascript' src='/joli/js/plugins/icheck/icheck.min.js'></script>
<script>
    function validateForm() {
        /*var email = $("#user_email").val();
        var name = $("#user_name").val();
        var mobile = $("#user_mobile").val();*/

        $("#btnSearch").attr("disabled", true);
        //return false;
        //$("#loader").addClass("loader").fadeOut("slow");

        //if(email || name || mobile || address) return true;
        //return false;
    }
</script>