<?php
$this->headTitle("Thêm mới cửa hàng");
$form = $this->form;
$form->setAttributes([
    'enctype'=>'multipart/form-data'
]);
$form->prepare();
?>
<style>.error{color: red}</style>
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('user-dashboard')?>">Home</a></li>
    <li><a href="<?=$this->url('grocery-user',['action'=>'list','id'=>$this->groceryCat->getId()])?>">Danh sách cửa hàng</a></li>
    <li class="active">Thêm mới cửa hàng</li>
</ul>
<!-- END BREADCRUMB -->

<div class="page-title">
    <h3><span class="fa fa-arrow-circle-o-left"></span> Thêm mới cửa hàng cho tuyến <?=$this->groceryCat->getName()?></h3>
</div>
<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <?php
            if(count($this->flashMessenger()->getErrorMessages())>0){
                ?>
                <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->getErrorMessages()[0]?>
                </div>
                <?php
            }
            ?>
        </div>
        <div class="panel panel-default">
            <?=$this->form()->openTag($form)?>
            <div class="panel-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Tên cửa hàng (*):</label>
                    <div class="col-md-9">
                        <?php
                        echo $this->formElement($form->get('grocery_name'));
                        echo $this->formElementErrors($form->get('grocery_name'),['class' => 'error']);
                        ?>
                    </div>
                </div>
                <!--Address-->
                <div class="form-group">
                    <label class="col-md-3 control-label">Địa chỉ cửa hàng (*):</label>
                    <div class="col-md-9">
                        <?php
                        echo $this->formElement($form->get('address'));
                        echo $this->formElementErrors($form->get('address'),['class' => 'error']);
                        ?>
                    </div>
                </div>

                <div class="form-group">
                    <label for="owner_name" class="col-md-3 control-label">Tên chủ cửa hàng (*):</label>
                    <div class="col-md-9">
                        <?php
                        echo $this->formElement($form->get('owner_name'));
                        echo $this->formElementErrors($form->get('owner_name'),['class' => 'error']);
                        ?>
                    </div>
                </div>

                <!--Mobile-->
                <div class="form-group">
                    <label class="col-md-3 control-label">Điện thoại chủ (*):</label>
                    <div class="col-md-9">
                        <?php
                        echo $this->formElement($form->get('mobile'));
                        echo $this->formElementErrors($form->get('mobile'),['class' => 'error']);
                        ?>
                        <span id="mobile-msg" class="label label-success label-form"></span>
                    </div>
                </div>

                <!--Delivery note-->
                <div class="form-group">
                    <label class="col-md-3 control-label">Ghi chú giao hàng:</label>
                    <div class="col-md-9">
                        <?php
                        echo $this->formElement($form->get('delivery_note'));
                        echo $this->formElementErrors($form->get('delivery_note'),['class' => 'error']);
                        ?>
                    </div>
                </div>

                <!-- Image -->
                <div class="form-group">
                    <label class="col-md-3 control-label">Hình ảnh cửa hàng</label>
                    <div class="col-md-4">
                        <?php
                        echo $this->formElement($form->get('imageFile'));
                        echo $this->formElementErrors($form->get('imageFile'),['class' => 'error']);
                        ?>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="btnSubmit"  id="btnSubmit" class="btn btn-success" value="Thêm cửa hàng">
                        <span class="error" id="errorMessage"></span>
                    </div>
                </div>
            </div>
            <?=$this->form()->closeTag()?>
        </div>
    </div>
</div>
<script type="text/javascript" src="/joli/js/plugins/fileinput/fileinput.min.js"></script>
<script type='text/javascript' src='/joli/js/plugins/jquery-validation/jquery.validate.js'></script>
<script>
    $( document ).ready(function() {
        $("#imageFile").fileinput({
            showUpload: false,
            showCaption: false,
            browseClass: "btn btn-danger",
            fileType: "any"
        });

        let jvalidate = $("#grocery-form").validate({
            ignore: [],
            rules: {
                grocery_name: {
                    required: true
                },
                address: {
                    required: true
                },
                owner_name: {
                    required: true
                },
                mobile: {
                    required: true
                }
            }
        });

        $("#mobile").on('change keyup paste', function() {
            let mobile =$(this).val();
            if(mobile.length<10){
                $('#mobile-msg').addClass('label-danger');
                $('#mobile-msg').html('Số điện thoại không đúng!')
                return;
            }

            $('#mobile-msg').html('')

            let url='<?=$this->url('grocery-user',['action'=>'mobile-check'])?>';
            $.ajax({
                method: "GET",
                data: {mobile:mobile},
                url: url
            }).done(function(res) {
                if(res.status==1){
                    $('#mobile-msg').removeClass('label-danger');
                    console.log(res.message);
                }else{
                    $('#mobile-msg').addClass('label-danger');
                    //$('#mobile-msg').html(res.message);
                }
                $('#mobile-msg').html(res.message);
                // stop_waitMe();
            });
        });
    })

</script>