
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('user-dashboard')?>">Home</a></li>
    <li><a href="<?=$this->url('grocery-user')?>">Danh sách tuyến</a></li>
    <li><a href="<?=$this->url('grocery-user',['action'=>'list','id'=>$this->grocery->getGroceryCat()->getId()])?>">Danh sách cửa hàng</a></li>
    <li><a href="<?=$this->url('grocery-user',['action'=>'panel','id'=>$this->grocery->getId()])?>">Chức năng</a></li>
    <li>Check in</li>
</ul>

<div class="page-title">
    <h3><span class="fa fa-arrow-circle-o-left"></span> <?=$this->escapeHtml($this->grocery->getGroceryName())?></h3>
</div>
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <i class="fa fa-map-marker" style="padding-left: 10px"> <?=$this->escapeHtml($this->grocery->getAddress())?></i>
            <?php
            if(strlen($this->errMessage)>0){
                ?>
                <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->errMessage?>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <?php
            if(count($this->flashMessenger()->getSuccessMessages())>0){
                ?>
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->getSuccessMessages()[0]?>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-body" style="text-align: center">
                <?php
                if(strlen($this->errMessage)>0){
                ?>
                    <div id="reCheckIn">
                        <span class="fa fa-sign-out" style="font-size: 40px"></span><br>
                        <b>Check in lại</b>
                    </div>
                <?php
                }else{
                ?>
                    <p><span class="fa fa-cogs fa-spin"></span></p>
                    <div class="progress">
                        <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>

                    <div>
                        <div id="checkOut" class="pull-left">
                            <span class="fa fa-sign-out" style="font-size: 40px"></span><br>
                            <b>Check out</b>
                            <div id="firstTime"></div>
                            <div id="lastTime"></div>
                            <div id="time"></div>
                        </div>
                        <div class="pull-left" style="padding-left: 20px; padding-right: 10px;">
                            <a href="<?=$this->url('sell-user',['action'=>'add-draft-order','id'=>$this->grocery->getId()])?>#ci" style="color: #0d0d0d">
                                <span class="fa fa-money" style="font-size: 40px"></span><br>
                                <b>Tạo đơn hàng</b>
                            </a>
                        </div>
                    </div>
                <?php }?>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        $( "#checkOut" ).click(function() {
            run_waitMe();
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(
                    function(position){
                        stop_waitMe();
                        location.href="<?=$this->url('grocery-user',['action'=>'check-out','id'=>$this->grocery->getId()])?>?lat="+position.coords.latitude+"&lng="+position.coords.longitude;
                    },
                    function(error) {
                        alert('<?=$this->translate("Turn on location services to use this function.")?>');
                        stop_waitMe();
                    }
                );
            }
        })

        $( "#reCheckIn" ).click(function() {
            run_waitMe();
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(
                    function(position){
                        stop_waitMe();
                        location.href="<?=$this->url('grocery-user',['action'=>'check-in','id'=>$this->grocery->getId()])?>?lat="+position.coords.latitude+"&lng="+position.coords.longitude;
                    },
                    function(error) {
                        alert('<?=$this->translate("Turn on location services to use this function.")?>');
                        stop_waitMe();
                    }
                );
            }
        })

        var firstTime = parseFloat(<?=$this->checkIndate?>)*1000;
        // console.log(firstTime)
        // $('#firstTime').html(firstTime);

        var interval = setInterval(function() {
            var lastTime=new Date().getTime();
            var changeTime=lastTime-firstTime;
            // console.log(changeTime);
            var percentProcess =parseFloat(changeTime/6000).toFixed(2)
            if(percentProcess>=100) percentProcess=100;

            // $('#lastTime').html(lastTime);
            // $('#time').html(parseFloat(changeTime/60000).toFixed(2)+' phut');

            $( "div.progress-bar" ).attr( "aria-valuenow",percentProcess );
            $(".progress-bar").css("width", percentProcess+"%");
            $(".progress-bar").html(percentProcess+"%");

            if(percentProcess==100){
                clearInterval(interval);
                /*run_waitMe();
                if (navigator.geolocation) {
                    navigator.geolocation.getCurrentPosition(
                        function(position){
                            $.ajax({
                                method: "get",
                                url: "<?=$this->url('grocery-user',['action'=>'check-out','id'=>$this->grocery->getId()])?>",
                                data: { lat: position.coords.latitude,lng: position.coords.longitude, call:"ajax"}
                            }).done(function(response) {
                                stop_waitMe();
                            });
                        },
                        function(error) {
                            alert('<?=$this->translate("Turn on location services to use this function.")?>');
                            stop_waitMe();
                        }
                    );
                }*/

            }
        }, 3000);//3s to run

    });
</script>