<?php
use Sulde\Service\Common\Common;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>NPP ANH VŨ</title>
    <meta name="viewport" content="width&#x3D;device-width,&#x20;initial-scale&#x3D;1.0">
    <meta http-equiv="X-UA-Compatible" content="IE&#x3D;edge">
    <!-- Le styles -->
    <link href="&#x2F;favicon.png" rel="shortcut&#x20;icon" type="image&#x2F;x-icon">

    <!-- CSS INCLUDE -->
    <link rel="stylesheet" type="text/css" id="theme" href="/joli/css/theme-default.css"/>

    <!-- START SCRIPTS -->
    <!-- START PLUGINS -->
    <script type="text/javascript" src="/joli/js/plugins/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/joli/js/plugins/jquery/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/joli/js/plugins/bootstrap/bootstrap.min.js"></script>
    <!-- END PLUGINS -->

    <!-- THIS PAGE PLUGINS -->
    <script type="text/javascript" src="/joli/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>
    <!-- END PAGE PLUGINS -->

    <!-- START TEMPLATE -->
    <script type="text/javascript" src="/joli/js/plugins.js"></script>
    <script type="text/javascript" src="/joli/js/actions.js"></script>

    <link href="/vendor/jquery/waitMe/waitMe.css" rel="stylesheet">
    <script src="/vendor/jquery/waitMe/waitMe.js"></script>
    <script type="text/javascript" src="/js/admin.js"></script>
    <!-- END TEMPLATE -->
    <!-- END SCRIPTS -->

</head>
<body>
<div id="wrapper">
    <div id="header">
        <a href="/users/dashboard.html" style="padding-top: 2px">
            <img src="/img/logo-user-admin.png" width="80px">
        </a>
    </div>
    <div id="map-canvas"></div>
</div>
</body>
</html>
<style>
    html, body, #wrapper{
        height: 100%;
        width: 100%;
    }
    #header{
        background-color:#ff6700;
        padding:5px;
        margin:10px;
        position: absolute;
        z-index: 1000;
    }
    #map-canvas{
        height: 100%;
        width: 100%;
    }
</style>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=<?=$this->geoKey?>&callback=initMap"></script>

<?php
$data=[];
if($this->groceryList){
    $dateNow=strtotime(date("Y-m-d"));
    foreach ($this->groceryList as $grocery=>$groceryItem) {
        if(!is_null($groceryItem->getLat()) && !is_null($groceryItem->getLng())){
            $arrTam["name"]=$groceryItem->getGroceryName();
            $arrTam["url"]=$this->url('grocery-user',['action'=>'panel','id'=>$groceryItem->getId()]);
            $arrTam["lat"]=$groceryItem->getLat();
            $arrTam["lng"]=$groceryItem->getLng();
            $arrTam["check_in_date"]=Common::formatDateTime(@$groceryItem->getCheckInDate());

            if($groceryItem->getCheckInDate())
                $checkInDate =strtotime($groceryItem->getCheckInDate()->format('Y-m-d'));
            else
                $checkInDate=0;

            if($dateNow==$checkInDate)
                $arrTam["icon"]='icon-grocery-blue.png';
            else if($groceryItem->getCheckInDate())
                $arrTam["icon"]='icon-grocery-yeallow.png';
            else
                $arrTam["icon"]='icon-grocery-red.png';

            $data[]=$arrTam;
        }
    }

}
?>
<script>
    var map;
    var dataObj = jQuery.parseJSON( '<?=json_encode($data)?>' );
    var myStyles =[
        {
            featureType: 'poi.business',
            stylers:  [
                { visibility: "off" }
            ]
        },{
            featureType: 'poi.attraction',
            elementType: 'labels.text.fill',
            stylers: [{color: '#e28b0b'}]
        },{
            featureType: "administrative",
            stylers: [
                { visibility: "off" }
            ]
        }
    ];
    function initMap() {
        map = new google.maps.Map(document.getElementById('map-canvas'), {
            disableDefaultUI: true,
            fullscreenControl: true,
            zoom: 15,
            styles: myStyles
        });

        var bounds = new google.maps.LatLngBounds();
        $.each(dataObj, function (key, data) {
            var latLng = new google.maps.LatLng(data.lat, data.lng);
            var marker = new google.maps.Marker({
                map: map,
                position: latLng,
                icon:{
                    url:"/img/icons/"+data.icon,
                    scaledSize: new google.maps.Size(35, 35)
                }
            });

            var infowindow = new google.maps.InfoWindow({
                content: '<div id="content"><a target="_blank" href="'+data.url+'">'+data.name+'</a> <br><i>Checkin: '+data.check_in_date+'</i></div>'
            });

            marker.addListener("click", () => {
                infowindow.open(map, marker);
            });
            bounds.extend(latLng);
        });
        map.fitBounds(bounds);

        <?php if($this->groceryCat->getPolygon()){?>
        const triangleCoords = jQuery.parseJSON('<?=$this->groceryCat->getPolygon()?>');

        // Construct the polygon.
        const bermudaTriangle = new google.maps.Polygon({
            paths: triangleCoords,
            strokeColor: "#0a65ee",
            strokeOpacity: 0.8,
            strokeWeight: 2,
            fillColor: "#4590f3",
            fillOpacity: 0.25,
        });

        bermudaTriangle.setMap(map);
        <?php } ?>

        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function (position) {

                var center = new google.maps.LatLng(position.coords.latitude,
                    position.coords.longitude);

                var marker = new google.maps.Marker({
                    map: map,
                    position: center,
                    icon: {
                        path: google.maps.SymbolPath.CIRCLE,
                        scale: 8,
                        strokeColor: 'white',
                        strokeWeight: 2,
                        fillColor: '#1A73E8',
                        fillOpacity: 0.6
                    }
                });
                marker.setMap(map);
                marker.setPosition(center);

                var markerWaveCurrent = new google.maps.Marker({
                    icon: {
                        path: google.maps.SymbolPath.CIRCLE,
                        scale: 0,
                        strokeColor: 'white',
                        strokeWeight: 1,
                        fillColor: '#1A73E8',
                        fillOpacity: 0.3
                    },
                });
                markerWaveCurrent.setMap(map);
                markerWaveCurrent.setPosition(center);

                var count=0;
                window.setInterval(function() {
                    var icon = markerWaveCurrent.get('icon');
                    if(icon.scale<30){
                        icon.scale = icon.scale+1;
                    }else{
                        count = count+1;
                        icon.scale = 8;
                    }
                    markerWaveCurrent.set('icon', icon);
                }, 35);

            }, function () {
                handleLocationError(true, infowindow, map.getCenter());
                // stop_waitMe();
            });
        } else {
            // Browser doesn't support Geolocation
            handleLocationError(false, infowindow, map.getCenter());
            // stop_waitMe();
        }
    }
</script>
