<?php
use Sulde\Service\Common\Common;
use Zend\Mvc\Plugin\FlashMessenger\FlashMessenger;

?>
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('sell-front')?>">Home</a></li>
</ul>
<div class="page-title">
    <h3><span class="fa fa-arrow-circle-o-left"></span> <?=$this->sellOrder->getOrderCode()?> | <?=$this->sellOrder->getGrocery()->getGroceryName()?></h3>
    <small style="padding-left: 15px"><?=$this->sellOrder->getGrocery()->getAddress()?></small>
</div>

<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <?php
            if($this->flashMessenger()->render(FlashMessenger::NAMESPACE_SUCCESS)){
                ?>
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->render(FlashMessenger::NAMESPACE_SUCCESS)?>
                </div>
                <?php
            }
            if($this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR)){
                ?>
                <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR)?>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
    <div class="row">
        <?php
        $noteArr =explode("\n",$this->sellOrder->getNote());
        if($this->sellOrder->getNote()){
        ?>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <?php
                        echo '<div class="alert alert-danger" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>';
                        foreach ($noteArr as $value){
                            $arrNote = explode("|",$value);
                            echo "<b>".@$arrNote[0] ."</b>";
                            echo " [<i>".Common::formatDateTime(@$arrNote[1])."</i>]";
                            echo '<span>'.@$arrNote[2].'</span>';
                        }
                        echo '</div>';
                    ?>
                </div>
            </div>
        </div>
        <?php
        }
        ?>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="<?=$this->url('sell-front',['action'=>'confirm-delivery','id'=>$this->sellOrder->getId()])?>" class="btn btn-success">
                        <span class="fa fa-truck"></span>
                        Xác nhận đã giao hàng
                    </a>
                    <button type="button" class="btn btn-info directions" id="directions">
                        <span class="fa fa-hand-o-right"></span>
                        Chỉ đường
                    </button>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <ul id="productList" class="list-group">
                <?php
                foreach ($this->sellOrder->getSell() as $sell){
                    ?>
                    <li href="#" class="list-group-item">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1 title"><?=$sell->getProduct()->getCode()?> | <?=$sell->getProduct()->getName()?> | <?=$sell->getProduct()->getWeight()?></h5>
                        </div>
                        <table style="width: 100%">
                            <tbody>
                            <tr>
                                <td style="padding-right: 5px; width: 40px">
                                    <img src="<?=$sell->getProduct()->getImg()?>" style="max-width:40px; max-height:30px">
                                </td>
                                <td>
                                    <table style=" width: 100%;" >
                                        <tbody>
                                        <tr>
                                            <td style="padding-left: 10px;" nowrap="">Giá bán:</td>
                                            <td style="padding-left: 10px; padding-right: 10px" nowrap="">Số lượng:</td>
                                            <td style="padding-left: 5px">Thành tiền:</td>
                                        </tr>
                                        <tr>
                                            <td style="padding-left: 10px; font-weight: bold;" nowrap=""><?=Common::formatMoney($sell->getPrice()->getPrice())?> đ
                                            </td>
                                            <td style="padding-left: 10px;"><?=$sell->getQuantity().' '.$sell->getProduct()->getUnit()->getName()?> <small class="warning-color"><?=($sell->getReturn()>0?' (Trả lại: '.$sell->getReturn().')':'')?></small></td>
                                            <?php
                                            $totalMoney=$sell->getQuantity()*$sell->getPrice()->getPrice();
                                            ?>
                                            <td style="padding-left: 5px"><?=Common::formatMoney($totalMoney)?> đ</td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <small id="msg15" class="warning-color"></small>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </li>
                    <?php
                }
                ?>
                <li href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1 title" style="color: #26a9d1; text-align: right">Tổng đơn: <?=Common::formatMoney(round($this->sellOrder->getTotalPrice()/1000)*1000)?> đ</h5>
                    </div>
                </li>
            </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .list-group{font-size: 14px}
    .list-group-item .title{font-weight: bold; font-size: 14px}
    .list-group .list-group-item:last-child{
        border-bottom: 1px solid #E5E5E5;
    }
    .price{color: #26a9d1; font-weight: bold; padding-left: 10px}
    .warning-color{color: red}
</style>

<script>
    $(document).ready(function() {
        $( ".directions" ).click(function() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(
                    function(position){
                        var currentLocal = position.coords.latitude+','+ position.coords.longitude;
                        var groceryLocal = '<?=$this->sellOrder->getGrocery()->getLat().','.$this->sellOrder->getGrocery()->getLng()?>';
                        var url = 'https://www.google.com/maps/dir/?api=1&origin='+currentLocal+'&destination='+groceryLocal;
                        window.location.href =url;
                    },
                    function(error) {
                        alert('<?=$this->translate("Turn on location services to use this function.")?>');
                    }
                );
            }
        });
    });
</script>