<?php

use Sulde\Service\Common\Common;
use Sulde\Service\Common\ConfigManager;

$this->headTitle("Thông tin sản phẩm");
?>
<style>.error{color: red}</style>
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('admin-dashboard')?>">Home</a></li>
    <li><a href="<?=$this->url('product-admin')?>">Danh sách sản phẩm</a></li>
    <li class="active">Thông tin sản phẩm</li>
</ul>
<!-- END BREADCRUMB -->

<div class="page-title">
    <h3><span class="fa fa-arrow-circle-o-left"></span> Thông tin sản phẩm <?=$this->product->getName()?> </h3>
</div>
<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <?php
            if(count($this->flashMessenger()->getErrorMessages())>0){
                ?>
                <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->getErrorMessages()[0]?>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Thông tin sản phẩm</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Tên sản phẩm:</label>
                                <div class="col-md-9 font-weight-bold">
                                    <a href="<?=$this->url('product-admin',['action'=>'edit-price','id'=>$this->product->getId()])?>">
                                    <?=$this->product->getName().' | '.$this->product->getWeight()?>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Mã sản phẩm:</label>
                                <div class="col-md-9"><?=$this->product->getCode()?></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Mã thùng:</label>
                                <div class="col-md-9"><?=$this->product->getPackCode()?></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Mã sản phẩm 1:</label>
                                <div class="col-md-9"><?=$this->product->getCode1()?></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Mã sản phẩm 2:</label>
                                <div class="col-md-9"><?=$this->product->getCode2()?></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Mã sản phẩm 3:</label>
                                <div class="col-md-9"><?=$this->product->getCode3()?></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Loại:</label>
                                <div class="col-md-9"><?=$this->product->getProductCat()->getName()?></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Đơn vị:</label>
                                <div class="col-md-9"><?=$this->product->getUnit()->getName()?></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Trọng lượng:</label>
                                <div class="col-md-9"><?=$this->product->getWeight()?></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Quy cách:</label>
                                <div class="col-md-9"><?=$this->product->getBoxUnit() .' '.$this->product->getUnit()->getName()?></div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Giá vốn:</label>
                                <div class="col-md-9"><?=Common::formatMoney($this->product->getAveragePrice())?></div>
                            </div>
                        </div>

                        <div class="form-group" >
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right text-info">Giá bán:</label>
                                <div class="col-md-9 text-info font-weight-bold"><?=Common::formatMoney($this->product->getActivePriceValue())?> đ</div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Giảm giá lẻ:</label>
                                <div class="col-md-9 text-danger">
                                    <?=$this->product->getUnitSaleValueString()?>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right text-info">Giá lẻ sau giảm:</label>
                                <div class="col-md-9">
                                    <span class="text-info font-weight-bold"><?=Common::formatMoney($this->product->getUnitPriceAfterSale())?> đ</span>
                                    <small class="help-block">= Giá bán - Giảm giá lẻ</small>
                                </div>
                            </div>
                        </div>

                        <div class="form-group" >
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Giá thùng:</label>
                                <div class="col-md-9"><?=Common::formatMoney($this->product->getPackPrice())?> đ</div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Giảm giá thùng:</label>
                                <div class="col-md-9 text-danger">
                                    <?=$this->product->getPackSaleValueString()?>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right text-info">Giá thùng sau giảm:</label>
                                <div class="col-md-9">
                                    <span class="text-info font-weight-bold"><?=Common::formatMoney($this->product->getPackPriceAfterSale())?> đ</span>
                                    <small class="help-block">= Giá thùng - Giảm giá thùng</small>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Tồn kho:</label>
                                <div class="col-md-9"><?=$this->product->getInventory().' '.$this->product->getUnit()->getName()?></div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Bán lẻ tối thiếu:</label>
                                <div class="col-md-9"><?=$this->product->getExchangeUnit().' '.$this->product->getUnit()->getName()?></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Định mức:</label>
                                <div class="col-md-9">
                                    <?=$this->product->getNorm()?>
                                    <small class="help-block">Tồn kho thấp hơn định mức thì hệ thống sẽ đưa sản phẩm vào danh sách cần nhập</small>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="name" class="col-md-3 control-label text-right">Định mức nhập:</label>
                                <div class="col-md-9">
                                    <?=$this->product->getNormInput()?>
                                    <small class="help-block">Định mức nhập tối thiểu</small>
                                </div>
                            </div>
                        </div>
                        <?php if($this->product->getImg()){ ?>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-12"><img src="<?=$this->product->getImg()?>" width="90%"></div>
                                </div>
                            </div>
                        <?php }?>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Lịch sử giá</h3>
                </div>
                <div class="panel-body">
                        <?php
                        foreach ($this->product->getPrice() as $price){
                            ?>
                                <div class="row">
                                    <div class="col-md-4" style="padding: 5px; border-bottom: 1px solid #f5f5f5">
                                        <?php
                                        if($price->getActive()==1)
                                            echo '<i class="fa fa-check-circle-o" style="color: #00e25b; font-size: large"></i>';
                                        else
                                            echo '<i class="fa fa-check-circle-o" style="color: #f5f5f5; font-size: large"></i>';
                                        ?>
                                        <?=Common::formatMoney($price->getPrice());?>
                                    </div>
                                    <div class="col-md-4" style="padding: 5px; border-bottom: 1px solid #f5f5f5"><?=Common::formatDateTime($price->getCreatedDate());?></div>
                                    <div class="col-md-4" style="padding: 5px; border-bottom: 1px solid #f5f5f5"><?=$price->getUser()->getFullname();?></div>
                                </div>

                        <?php
                        }
                        ?>
                </div>
            </div>            
        </div>
    </div>    
</div>
<style>
    .font-weight-bold{font-weight: bold}
</style>
<script type="text/javascript" src="/joli/js/plugins/morris/raphael-min.js"></script>
<script type="text/javascript" src="/joli/js/plugins/morris/morris.min.js"></script>
<script type="text/javascript" src="/joli/js/plugins/datatables/jquery.dataTables.2.1.8.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/dataTables.dataTables.css"/>
<style>
    .dt-length label{display: none!important;}
    .dt-length select{width: 50px;}
    .red{color: red}
    .blue{color: blue}
</style>

<script>
    $(document).ready(function () {
        
    });
</script>