<html lang="en">
<head>
    <title>product price</title>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html;" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- END META SECTION -->

</head>
<body>
<?php
use Sulde\Service\Common\Common;
?>
<div class="modal"></div>
<div>
    <div class="row">
        <div class="panel panel-default" style="padding-bottom: 10px">
            <div class="panel-body">
                <table style="width: 100%">
                    <tr>
                        <td style="width: 50%" nowrap="">
                            <h4 style="padding-bottom: 0px; margin-bottom: 5px">
                                <a style="color: #000000; text-decoration:unset" href="<?=$this->url('product-user',['action'=>'export-price'])?>">NHÀ PHÂN PHỐI ANH VŨ - BẢNG BÁO GIÁ SẢN PHẦM</a>
                            </h4>
                            <div style="padding-bottom: 3px"><b>Địa chỉ:</b> KĐT Thanh Hà, Hà Đông, TP. Hà Nội</div>

                        </td>
                        <td style="width: 50%; text-align: right">
                            <div style="padding-bottom: 3px">Điện thoại: <b>0946 021 021</b> Zalo: <b>0877 427 569</b></div>
                            <div style="padding-bottom: 5px;"><b id="btnSubmit" style="cursor: pointer">Áp dụng từ: </b><i>Ngày <?=date("d")?> tháng <?=date("m")?> năm <?=date("Y")?></i></div>
                        </td>
                    </tr>
                </table>

            </div>
        </div>
    </div>
    <div class="row">
        <div class="panel panel-default">
            <div class="info-order">
                <table id="tblPrice" style="width: 100%;">
                    <tr>
                        <?php
                        $i=1;
                        $colLeft='';
                        $colRight='';
                        foreach ($this->product as $product){
                            if($product->getActive()==1){
                                if($product->getSortPriceTable()%2>0)
                                    $colLeft.=rowItem($product);
                                else
                                    $colRight.=rowItem($product);
                            }
                        }

                        function rowItem($product){
                            $li = '<li data-id="' . $product->getId() . '">';
                            $li.='<table style="width: 100%">';
                            $li.='<tr>';

                            if(is_null($product->getImg()))
                                $li.='<td><img src="/img/icons/no-image-icon.png" class="pull-left" width="40px"></td>';
                            else
                                $li.='<td><img src="'.$product->getImg().'" style ="max-width:40px; max-height:30px"></td>';

                            $li.='<td style="width: 100%">'.$product->getName() . " | " . $product->getWeight().'</td>';
                            $li.='<td>'.Common::formatMoney($product->getActivePrice()->getPrice()).'</td>';

                            $li.='</tr>';
                            $li.='</table>';
                            $li.='</li>';
                            return $li;
                        }
                        ?>
                        <td style="width: 50%; vertical-align:top;">
                            <ol id="colLeft" class="simple_with_animation vertical" style="padding-left: 0px; border: 1px solid blue">
                                <?=$colLeft?>
                            </ol>
                        </td>
                        <td style="width: 50%; vertical-align:top">
                            <ol id="colRight" class="simple_with_animation vertical" style="padding-left: 0px; border: 1px solid blue">
                                <?=$colRight?>
                            </ol>
                        </td>
                    </tr>
                </table>
            </div>
            <div class="info-sender" style="text-align: right; padding-top: 15px">
                <i>RẤT HÂN HẠNH ĐƯỢC PHỤC VỤ QUÝ KHÁCH!</i>
            </div>
        </div>
    </div>
</div>
<style>
    body {
        font-family: "Times New Roman";
        font-size: 14px;
    }
    body.dragging, body.dragging * {
        cursor: move !important;
    }
    .dragged {
        position: absolute;
        opacity: 0.5;
        z-index: 2000;
    }

    ol.simple_with_animation li, ol.serialization li, ol.default li {
        cursor: pointer;
    }
    ol li.highlight {
        background: #333333;
        color: #999999;
    }
    ol.vertical li {
        display: block;
        margin: 5px;
        padding: 5px;
        border: 1px solid #cccccc;
        color: #0088cc;
    }

    /*loading*/
    .modal {
        display:    none;
        position:   fixed;
        z-index:    1000;
        top:        0;
        left:       0;
        height:     100%;
        width:      100%;
        background: rgba( 255, 255, 255, .8 )
        url('/img/logo.png')
        50% 50%
        no-repeat;
    }

    /* When the body has the loading class, we turn
       the scrollbar off with overflow:hidden */
    body.loading {
        overflow: hidden;
    }

    /* Anytime the body has the loading class, our
       modal element will be visible */
    body.loading .modal {
        display: block;
    }
</style>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript" src="https://johnny.github.io/jquery-sortable/js/jquery-sortable.js"></script>
<script type="text/javascript">
    $( document ).ready(function() {
        $body = $("body");
        var adjustment;
        $("ol.simple_with_animation").sortable({
            group: 'simple_with_animation',
            pullPlaceholder: false,
            // animation on drop
            onDrop: function  ($item, container, _super) {
                var $clonedItem = $('<li/>').css({height: 0});
                $item.before($clonedItem);
                $clonedItem.animate({'height': $item.height()});

                $item.animate($clonedItem.position(), function  () {
                    $clonedItem.detach();
                    _super($item, container);
                });
            },

            // set $item relative to cursor position
            onDragStart: function ($item, container, _super) {
                var offset = $item.offset(),
                    pointer = container.rootGroup.pointer;

                adjustment = {
                    left: pointer.left - offset.left,
                    top: pointer.top - offset.top
                };

                _super($item, container);
            },
            onDrag: function ($item, position) {
                $item.css({
                    left: position.left - adjustment.left,
                    top: position.top - adjustment.top
                });
            }
        });


        $('#btnSubmit').click(function(){
            $body.addClass("loading");
            var sortList=[];

            $('#colLeft li').each(function(i){
                $index=$(this).index()*2+1;
                sortList.push({
                    id:$(this).data('id'),
                    index: $index
                });
            });
            $('#colRight li').each(function(i){
                $index=$(this).index()*2+2;
                sortList.push({
                    id:$(this).data('id'),
                    index: $index
                });
            });

            var url = "<?=$this->url('product-admin',['action'=>'sortable'])?>";
            $.post( url, {d: sortList }).done(function( data ) {
                $body.removeClass("loading");
            });
        })
    });
</script>
</body>
</html>