<?php

use Zend\Mvc\Plugin\FlashMessenger\FlashMessenger;

$title = "Report";
$this->headTitle($title);
?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('admin-dashboard')?>">Home</a></li>
    <li><a href="<?=$this->url('report-admin')?>">Report</a></li>
    <li class="active">Loại sản phẩm</li>
</ul>
<!-- END BREADCRUMB -->

<div class="page-title">
    <h3><span class="fa fa-arrow-circle-o-left"></span> Doanh thu theo loại sản phẩm</h3>
</div>

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <label class="col-md-1 text-right" style="padding-top: 5px">Ngày bắt đầu</label>
                    <div class="col-md-2">
                        <div class="input-group">
                            <input type="text" class="form-control" value="<?=$this->fdate?>" id="fdate" data-date-format="yyyy-mm-dd" data-date-viewmode="months">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                        </div>
                    </div>
                    <label class="col-md-2 text-right" style="padding-top: 5px">Ngày kết thúc</label>
                    <div class="col-md-2">
                        <div class="input-group">
                            <input type="text" class="form-control" value="<?=$this->tdate?>" id="tdate" data-date-format="yyyy-mm-dd" >
                            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <button id="btnSubmit" class="btn btn-success">Xem báo cáo</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div id="chart-9" style="height: 300px;"><svg></svg></div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div id="chart-10" style="height: 300px;"><svg></svg></div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="/joli/js/plugins/morris/raphael-min.js"></script>
<script type="text/javascript" src="/joli/js/plugins/morris/morris.min.js"></script>
<script type="text/javascript" src="/joli/js/plugins/bootstrap/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="/joli/js/plugins/nvd3/lib/d3.v3.js"></script>
<script type="text/javascript" src="/joli/js/plugins/nvd3/nv.d3.min.js"></script>
<script>
    $( document ).ready(function() {
        $("#tdate,#fdate").datepicker();

        $('#btnSubmit').click(function(){
            var url='<?=$this->url('report-admin',['action'=>'grocery'])?>?fd='+$('#fdate').val()+'&td='+$('#tdate').val();
            location.href=url;
        });

        var nvd3Charts = function() {

            var myColors = ["#33414E","#8DCA35","#00BFDD","#FF702A","#DA3610",
                "#80CDC2","#A6D969","#D9EF8B","#FFFF99","#F7EC37","#F46D43",
                "#E08215","#D73026","#A12235","#8C510A","#14514B","#4D9220",
                "#542688", "#4575B4", "#74ACD1", "#B8E1DE", "#FEE0B6","#FDB863",
                "#C51B7D","#DE77AE","#EDD3F2"];
            d3.scale.myColors = function() {
                return d3.scale.ordinal().range(myColors);
            };

            var startChart9 = function() {
                //Regular pie chart example
                nv.addGraph(function() {
                    var chart = nv.models.pieChart().x(function(d) {
                        return d.label;
                    }).y(function(d) {
                        return d.value;
                    }).showLabels(true).color(d3.scale.myColors().range());

                    d3.select("#chart-9 svg").datum(exampleData()).transition().duration(350).call(chart);

                    return chart;
                });

                //Donut chart example
                nv.addGraph(function() {
                    var chart = nv.models.pieChart().x(function(d) {
                        return d.label;
                    }).y(function(d) {
                        return d.value;
                    }).showLabels(true)//Display pie labels
                        .labelThreshold(.05)//Configure the minimum slice size for labels to show up
                        .labelType("percent")//Configure what type of data to show in the label. Can be "key", "value" or "percent"
                        .donut(true)//Turn on Donut mode. Makes pie chart look tasty!
                        .donutRatio(0.35)//Configure how big you want the donut hole size to be.
                        .color(d3.scale.myColors().range());;

                    d3.select("#chart-10 svg").datum(exampleData()).transition().duration(350).call(chart);

                    return chart;
                });

                //Pie chart example data. Note how there is only a single array of key-value pairs.
                function exampleData() {
                    return [<?php
                        foreach ($this->arrProCat as $value){
                            echo '{"label" : "'.$value["name"].'","value" : '.$value["price"].'},';
                        }
                        ?>];
                }

            };

            var startChart10 = function() {
                //Regular pie chart example
                nv.addGraph(function() {
                    var chart = nv.models.pieChart().x(function(d) {
                        return d.label;
                    }).y(function(d) {
                        return d.value;
                    }).showLabels(true).color(d3.scale.myColors().range());

                    d3.select("#chart-10 svg").datum(exampleData()).transition().duration(350).call(chart);

                    return chart;
                });

                //Donut chart example
                nv.addGraph(function() {
                    var chart = nv.models.pieChart().x(function(d) {
                        return d.label;
                    }).y(function(d) {
                        return d.value;
                    }).showLabels(true)//Display pie labels
                        .labelThreshold(.05)//Configure the minimum slice size for labels to show up
                        .labelType("percent")//Configure what type of data to show in the label. Can be "key", "value" or "percent"
                        .donut(true)//Turn on Donut mode. Makes pie chart look tasty!
                        .donutRatio(0.35)//Configure how big you want the donut hole size to be.
                        .color(d3.scale.myColors().range());

                    d3.select("#chart-10 svg").datum(exampleData()).transition().duration(350).call(chart);

                    return chart;
                });

                //Pie chart example data. Note how there is only a single array of key-value pairs.
                function exampleData() {
                    return [<?php
                        foreach ($this->arrProCat as $value){
                            echo '{"label" : "'.$value["name"].'","value" : '.$value["quantity"].'},';
                        }
                        ?>];
                }

            };
            return {
                init : function() {
                    startChart9();
                    startChart10();
                }
            };
        }();
        nvd3Charts.init();
    })
</script>
