<?php

use Zend\Mvc\Plugin\FlashMessenger\FlashMessenger;

$title = "Report";
$this->headTitle($title);
?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('admin-dashboard')?>">Home</a></li>
    <li><a href="<?=$this->url('report-admin')?>">Report</a></li>
    <li class="active">Zalo App</li>
</ul>
<!-- END BREADCRUMB -->

<div class="page-title">
    <h3><span class="fa fa-arrow-circle-o-left"></span> Doanh thu theo loại sản phẩm</h3>
</div>

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="col-md-2">
                        <a href="<?=$this->url('report-admin',['action'=>'install-app'])?>">
                            <p class="font-icon text-center"><span class="glyphicon glyphicon-floppy-open"></span></p>
                            <p class="title text-center">Install App</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<style>
    .font-icon{font-size: 30pt}
    .title{font-weight: bold}
</style>
<script>
    $( document ).ready(function() {

    })
</script>
