<?php

use Sulde\Service\Common\Common;
use Zend\Mvc\Plugin\FlashMessenger\FlashMessenger;

$title = "Chi tiết đơn giao";
$this->headTitle($title);
?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('staff-dashboard')?>">Home</a></li>
    <li><a href="<?=$this->url('sell-staff')?>">Danh sách đơn đang giao</a></li>
    <li class="active"><?=$title?></li>
</ul>
<!-- END BREADCRUMB -->
<div class="page-title">
    <h3><span class="fa fa-arrow-circle-o-left"></span> <?=$this->sellOrder->getOrderCode()?> | <?=$this->sellOrder->getGrocery()->getGroceryName()?></h3>
    <small style="padding-left: 15px"><?=$this->sellOrder->getGrocery()->getAddress()?></small>
</div>

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <?php
            if($this->flashMessenger()->render(FlashMessenger::NAMESPACE_SUCCESS)){
                ?>
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->render(FlashMessenger::NAMESPACE_SUCCESS)?>
                </div>
                <?php
            }
            if($this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR)){
                ?>
                <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR)?>
                </div>
                <?php
            }
            ?>
        </div>
    </div>

    <div class="row">
        <?php
        $noteArr =explode("\n",$this->sellOrder->getNote());
        if($this->sellOrder->getNote()){
            ?>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <?php
                        echo '<div class="alert alert-danger" role="alert">';
                        echo '<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>';
                        foreach ($noteArr as $value){
                            $arrNote = explode("|",$value);
                            echo "<b>".@$arrNote[0] ."</b>";
                            echo " [<i>".Common::formatDateTime(@$arrNote[1])."</i>]";
                            echo '<span>'.@$arrNote[2].'</span>';
                        }
                        echo '</div>';
                        ?>
                    </div>
                </div>
            </div>
            <?php
        }
        ?>
        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <?php
                    $zaloApp=$this->sellOrder->getGrocery()->getZaloAppItem();
                    $zaloAppNotify='Khách chưa cài ứng dụng đặt hàng, hãy gửi mã truy cập ứng dụng cho khách!';
                    if($zaloApp) $zaloAppNotify='';
                    ?>
                    <a style="margin-top: 5px" href="<?=$this->url('sell-staff',['action'=>'delivery-confirm','id'=>$this->sellOrder->getId()])?>" class="btn btn-success">
                        <span class="fa fa-truck" style="font-size: 25pt; padding-top: 5px"></span>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Xác nhận giao hàng</p>
                    </a>
                    <button style="margin-top: 5px" type="button" class="btn btn-info directions" id="directions">
                        <span class="fa fa-hand-o-right" style="font-size: 25pt; padding-top: 5px"></span>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Chỉ đường</p>
                    </button>

                    <a style="margin-top: 5px" href="<?=$this->url('grocery-user',['action'=>'update-position','id'=>$this->grocery->getId()])?>" class="btn btn-danger">
                        <span class="fa fa-map-marker" style="font-size: 25pt; padding-top: 5px"></span>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Cập nhật vị trí</p>
                    </a>
                    <div style="color: red; font-weight: bold; margin-top: 10px"><?=$zaloAppNotify?></div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <ul id="productList" class="list-group">
                        <?php
                        $totalProductDiscount=0;
                        foreach ($this->sellOrder->getSell() as $sell){
                            $totalProductDiscount+=$sell->getDiscount();
                            ?>
                            <li href="#" class="list-group-item">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1 title"><?=$sell->getProduct()->getCode()?> | <?=$sell->getProduct()->getName()?> | <?=$sell->getProduct()->getWeight()?></h5>
                                </div>
                                <table style="width: 100%">
                                    <tbody>
                                    <tr>
                                        <td style="padding-right: 5px; width: 40px">
                                            <img src="<?=$sell->getProduct()->getImg()?>" style="max-width:40px; max-height:30px">
                                        </td>
                                        <td>
                                            <table style=" width: 100%;" >
                                                <tbody>
                                                <tr>
                                                    <td style="padding-left: 10px;" nowrap="">Giá bán:</td>
                                                    <td style="padding-left: 10px; padding-right: 10px" nowrap="">Số lượng:</td>
                                                    <td style="padding-left: 5px">Thành tiền:</td>
                                                </tr>
                                                <tr>
                                                    <td style="padding-left: 10px; font-weight: bold;" nowrap=""><?=Common::formatMoney($sell->getPrice()->getPrice())?> đ
                                                    </td>
                                                    <td style="padding-left: 10px;"><?=$sell->getQuantity().' '.$sell->getProduct()->getUnit()->getName()?> <small class="warning-color"><?=($sell->getReturn()>0?' (Trả lại: '.$sell->getReturn().')':'')?></small></td>
                                                    <?php
                                                    $totalMoney=$sell->getQuantity()*$sell->getPrice()->getPrice();
                                                    ?>
                                                    <td style="padding-left: 5px"><?=Common::formatMoney($totalMoney)?> đ</td>
                                                </tr>
                                                </tbody>
                                            </table>
                                            <small id="msg15" class="warning-color"></small>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </li>
                            <?php
                        }
                        $isProductDiscount = $this->sellOrder->isProductDiscount();
                        $totalAmountToPaid=$total_order_price = $this->sellOrder->getTotalPrice();
                        ?>
                        <li href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                            <div class="form-group" style="padding-top: 10px; padding-right: 10px;">
                                <table>
                                    <?php
                                    if($isProductDiscount==1 || $this->sellOrder->getDiscount()>0) {
                                        echo '<tr>';
                                        echo '<td style="width: 100%"></td>';
                                        echo '<td style="text-align: right; padding-top: 5px" nowrap="">Tổng cộng:</td>';
                                        echo '<td style="text-align: right; padding-top: 5px; padding-left: 5px; font-weight: bold">' . Common::formatMoney($total_order_price) . '</td>';
                                        echo '</tr>';

                                        if ($isProductDiscount == 1) {
                                            echo '<tr>';
                                            echo '<td></td>';
                                            echo '<td style="text-align: right; padding-top: 3px; padding-bottom: 3px" nowrap="">Chiết khấu theo sản phẩm:</td>';
                                            echo '<td style="text-align: right; font-weight: bold; padding-top: 3px; padding-left: 5px;padding-bottom: 3px">' . Common::formatMoney($totalProductDiscount) . '</td>';
                                            echo '</tr>';
                                        }

                                        if ($this->sellOrder->getDiscount() > 0) {
                                            echo '<tr>';
                                            echo '<td></td>';
                                            echo '<td style="text-align: right; padding-top: 3px; padding-bottom: 3px" nowrap="">Chiết khấu theo đơn (' . round(($this->sellOrder->getDiscount() / $total_order_price) * 100, 2) . '%):</td>';
                                            echo '<td style="text-align: right; font-weight: bold; padding-top: 3px; padding-left: 5px; padding-bottom: 3px">' . Common::formatMoney($this->sellOrder->getDiscount()) . '</td>';
                                            echo '</tr>';
                                        }
                                        $totalAmountToPaid =round(($totalAmountToPaid-$totalProductDiscount-$this->sellOrder->getDiscount())/1000)*1000;
                                        echo '<tr>';
                                        echo '<td></td>';
                                        echo '<td style="text-align: right; padding-top: 3px; padding-bottom: 3px" nowrap="">Số tiền phải thanh toán:</td>';
                                        echo '<td style="text-align: right; font-weight: bold; padding-top: 3px; padding-left: 5px; padding-bottom: 3px">' . Common::formatMoney($totalAmountToPaid) . '</td>';
                                        echo '</tr>';
                                    }else{
                                        $totalAmountToPaid=round($totalAmountToPaid/1000)*1000;
                                        echo '<tr>';
                                        echo '<td style="width: 100%"></td>';
                                        echo '<td style="text-align: right; padding-top: 5px;" nowrap="">Số tiền phải thanh toán:</td>';
                                        echo '<td style="text-align: right; font-weight: bold; padding-top: 5px;padding-left: 5px;">' . Common::formatMoney($totalAmountToPaid) . '</td>';
                                        echo '</tr>';
                                    }
                                    ?>
                                </table>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .list-group{font-size: 14px}
    .list-group-item .title{font-weight: bold; font-size: 14px}
    .list-group .list-group-item:last-child{
        border-bottom: 1px solid #E5E5E5;
    }
    .price{color: #26a9d1; font-weight: bold; padding-left: 10px}
    .warning-color{color: red}
</style>

<script>
    $(document).ready(function () {
        $( ".directions" ).click(function() {
            if (navigator.geolocation) {
                navigator.geolocation.getCurrentPosition(
                    function(position){
                        var currentLocal = position.coords.latitude+','+ position.coords.longitude;
                        var groceryLocal = '<?=$this->sellOrder->getGrocery()->getLat().','.$this->sellOrder->getGrocery()->getLng()?>';
                        var url = 'https://www.google.com/maps/dir/?api=1&origin='+currentLocal+'&destination='+groceryLocal;
                        window.location.href =url;
                    },
                    function(error) {
                        alert('<?=$this->translate("Turn on location services to use this function.")?>');
                    }
                );
            }
        });
    });
</script>