<?php

use Sulde\Service\Common\Common;
use Zend\Mvc\Plugin\FlashMessenger\FlashMessenger;

$title = "Danh sách đơn đang giao";
$this->headTitle($title);
?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('staff-dashboard')?>">Home</a></li>
    <li class="active"><?=$title?></li>
</ul>
<!-- END BREADCRUMB -->
<div class="page-title">
    <h3><span class="fa fa-arrow-circle-o-left"></span> Danh sách đơn đã giao</h3>
</div>

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <label class="col-md-1 text-right" style="padding-top: 5px">Người giao</label>
                    <div class="col-md-2">
                        <div class="input-group">
                            <select class="form-control" id="deliveredBy">
                                <option value="23">TrinhND</option>
                                <option value="2">TruongHM</option>
                            </select>
                        </div>
                    </div>
                    <label class="col-md-1 text-right" style="padding-top: 5px">Ngày bắt đầu</label>
                    <div class="col-md-2">
                        <div class="input-group">
                            <input type="text" class="form-control" autocomplete="off" value="<?=$this->fromDate?>" id="fdate" data-date-format="yyyy-mm-dd" data-date-viewmode="months">
                            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                        </div>
                    </div>
                    <label class="col-md-1 text-right" style="padding-top: 5px">Ngày kết thúc</label>
                    <div class="col-md-2">
                        <div class="input-group">
                            <input type="text" class="form-control" autocomplete="off" value="<?=$this->toDate?>" id="tdate" data-date-format="yyyy-mm-dd" >
                            <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <button id="btnSubmit" class="btn btn-success">Xem báo cáo</button>                        
                    </div>        
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            <!-- START JUSTIFIED TABS -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title-box">
                        <h3>Tiền giao theo ngày</h3>
                </div>
                <div class="panel-body">
                    <table class="table nowrap table-hover display" style="width:100%" id="tblOrder">
                        <thead>
                        <tr>
                            <th>visible</th>
                            <th>STT</th>
                            <th>Ngày giao</th>
                            <th>Tiền giao</th>                            
                        </tr>
                        </thead>
                        <tbody>                        
                        </tbody>
                        <tfoot>
                            <tr>
                                <th colspan="3" style="text-align:right"></th>
                                <th></th>
                                <th colspan="2"></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
            <!-- END JUSTIFIED TABS -->
        </div>
    </div>
</div>
<style>
    .panel-body table tr td{
        vertical-align: middle;
    }
    .dt-length label{
        display: none;
    }
    .dt-length select{
        width: 50px;
        display: inline-block;
    }
</style>
<script type="text/javascript" src="/joli/js/plugins/datatables/jquery.dataTables.2.1.8.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/dataTables.dataTables.css"/>

<script type="text/javascript" src="/joli/js/plugins/bootstrap/bootstrap-datepicker.js"></script>

<script>
    $(document).ready(function () {

        $("#tdate,#fdate").datepicker();

        let stt=1;
        //let deliveredAmount=0;
        //let confirmAmount=0;
        let tblOrder =$('#tblOrder').DataTable({
            info:false,
            paging: true,
            pageLength:30,
            ordering: false,
            processing: true,
            serverSide: false,
            stateSave: true,
            autoWidth: false,
            order: [[0, 'desc']],
            language: {
                searchPlaceholder: ""
            },
            search: {
                return: true
            },
            columnDefs: [
                { name:'id', targets: 0, visible: false},
                { name:'stt', targets: 1, orderable: false},
                { name:'deliveried_date', targets: 2, className: 'title'},
                { name:'delivered_amount', className: 'price', targets: 3,createdCell:function (td, cellData, rowData, row, col){
                    $(td).html(formatPrice(cellData));
                }}                                

            ],
            ajax: {
                url: '<?=$this->url('sell-staff',['action'=>'delivered'])?>',
                type: 'POST',
                data: function (d) {
                    d.fdate = $('#fdate').val();
                    d.tdate = $('#tdate').val();
                    d.deliveredBy = $('#deliveredBy').val();
                },
                dataSrc: function (json) {
                    let data=[];
                    let i=1;
                    $.each( json, function( key, value ) {
                        let dataItem=[];
                        dataItem.push(value);
                        dataItem.push(stt++);
                        dataItem.push(value.delivered_date);
                        dataItem.push(value.total_price);

                        data.push(dataItem);
                    });
                    return data;
                }
            },
            footerCallback: function (row, data, start, end, display) {
                var api = this.api();

                // Remove the formatting to get integer data for summation
                var intVal = function (i) {
                    return typeof i === 'string' ? i.replace(/[\$,]/g, '') * 1 : typeof i === 'number' ? i : 0;
                };
                // Total over this page
                pageTotal = api
                    .column(3, { page: 'current' })
                    .data()
                    .reduce(function (a, b) {
                        return intVal(a) + intVal(b);
                    }, 0);

                // Update footer
                $(api.column(3).footer()).html(formatCurrency(pageTotal.toString()));
            }
        }).on('click', 'tbody tr', (e) => {
            let classList = e.currentTarget.classList;

            if (classList.contains('tr-selected')) {
                classList.remove('tr-selected');
            }
            else {
                tblOrder.rows('.tr-selected').nodes().each((row) => row.classList.remove('tr-selected'));
                classList.add('tr-selected');
            }
        });
        
        
        $('#btnSubmit').click(function(){
            let fdate=$('#fdate').val();
            let tdate=$('#tdate').val();
            if(fdate==='' || tdate===''){
                alert('Vui lòng chọn ngày bắt đầu và ngày kết thúc');
                return;
            }
            stt=1;
            //deliveredAmount=0;
            //confirmAmount=0;
            tblOrder.ajax.reload();
        })
    });
</script>