<?php

use Sulde\Service\Common\Common;

$title="Admin dashboard";
$this->headTitle($title);
?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li class="active">Admin dashboard</li>
</ul>
<!-- END BREADCRUMB -->

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12" id="panelButton">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="<?=$this->url('product-admin')?>" class="btn btn-default">
                        <i class="fa fa-barcode" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Sản phẩm</p>
                    </a>
                    <a href="<?=$this->url('product-user',['action'=>'export-price'])?>" class="btn btn-default">
                        <i class="fa fa-print" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">In báo giá</p>
                    </a>
                    <a href="<?=$this->url('sell-admin')?>" class="btn btn-default">
                        <i class="fa fa-tags" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Đơn hàng</p>
                    </a>
                    <a href="<?=$this->url('grocery-admin')?>" class="btn btn-default">
                        <i class="fa fa-shopping-cart" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Tạo đơn bán</p>
                    </a>

                    <a href="<?=$this->url('werehouse-admin',['action'=>'choice-supplier'])?>" class="btn btn-default">
                        <i class="fa fa-book" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Nhập kho</p>
                    </a>

                    <a href="<?=$this->url('grocery-admin',['action'=>'list'])?>" class="btn btn-default">
                        <i class="fa fa-users" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Khách hàng</p>
                    </a>

                    <a href="<?=$this->url('grocery-admin',['action'=>'cat-list'])?>" class="btn btn-default">
                        <i class="fa fa-random" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Tuyến</p>
                    </a>

                    <a href="<?=$this->url('report-admin')?>" class="btn btn-default">
                        <i class="fa fa-bar-chart-o" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Report</p>
                    </a>

                    <a href="<?=$this->url('sell-staff',['action'=>'select-delivery-car'])?>" class="btn btn-default">
                        <i class="fa fa-truck" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Đơn đang giao</p>
                    </a>

                    <a href="<?=$this->url('sell-staff',['action'=>'delivered'])?>" class="btn btn-default">
                        <i class="fa fa-trophy" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Đơn đã giao</p>
                    </a>

                    <a href="<?=$this->url('product-admin',['action'=>'recommend'])?>" class="btn btn-default">
                        <i class="glyphicon glyphicon-bullhorn" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Sản phẩm gợi ý trên APP</p>
                    </a>

                    <a href="<?=$this->url('product-admin',['action'=>'sortable'])?>" class="btn btn-default">
                        <i class="fa fa-sort" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Sort bảng giá</p>
                    </a>

                    <a href="<?=$this->url('product-user',['action'=>'export-price-sort'])?>" class="btn btn-default">
                        <i class="fa fa-sort-amount-asc" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Sort sản phẩm</p>
                    </a>

                    <a href="<?=$this->url('sell-admin',['action'=>'delivery-route'])?>" class="btn btn-default">
                        <i class="fa fa-code-fork" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Phân tuyến giao hàng</p>
                    </a>

                    <a href="<?=$this->url('sell-admin',['action'=>'delivered-route']).'?date='.(new \DateTime())->format('Y-m-d')?>" class="btn btn-default">
                        <i class="glyphicon glyphicon-send" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Bản đồ đã giao</p>
                    </a>

                    <a href="<?=$this->url('grocery-admin',['action'=>'map-location'])?>" class="btn btn-default">
                        <i class="glyphicon glyphicon-map-marker" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Cửa hàng gần nhất</p>
                    </a>

                    <a href="<?=$this->url('sell-check-admin')?>" class="btn btn-default">
                        <i class="fa fa-check-circle" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Kiểm đơn</p>
                    </a>

                </div>
            </div>
        </div>
    </div>

    <div class="page-title" style="padding-bottom: 20px;">
        <span id="btnModal" style="width: 30px" class="input-group-addon add-on">
            <span class="glyphicon glyphicon-calendar"></span> <?=$this->strReportDate?>
        </span>
    </div>
    <div class="row">
        <div class="col-md-4">
            <!-- START TABS -->
            <div class="panel panel-default tabs">
                <ul class="nav nav-tabs" role="tablist">
                    <li class="active"><a href="#tab-first" role="tab" data-toggle="tab">Doanh thu</a></li>
                    <li><a href="#tab-second" role="tab" data-toggle="tab">Lợi nhuận</a></li>
                </ul>
                <div class="panel-body tab-content">
                    <div class="tab-pane active" id="tab-first" style="text-align: center">
                        <div style="text-align: center"><span class="fa fa-signal" style="font-size: 100pt; color: #2db3dc"></span></div>
                        <h4>DOANH THU</h4>
                        <div style="color: #2db3dc; font-size: 18pt; font-weight: bold"><?=Common::formatMoney($this->totalRevenue)?></div>
                        <div><b>Tổng đơn hàng: <?=$this->orderNumber?></b></div>
                        <div style="text-align: left; padding-top: 30px"><b>Doanh thu:</b> Bằng tổng giá trị các đơn hàng giao thành công đã trừ trả hàng.</div>
                    </div>
                    <div class="tab-pane" id="tab-second" style="text-align: center">                        
                       <div id="morris-donut-cat" style="height: 300px; width:300px"></div>
                    </div>
                </div>
            </div>
            <!-- END TABS -->
        </div>     
    </div>
</div>

<!-- Modal -->
<div class="modal fade bottom" id="modalDate" tabindex="-1" role="dialog" aria-labelledby="modalDate" aria-hidden="true">
    <input id="local" value="" type="hidden">
    <div class="modal-dialog modal-bottom" role="document">
        <div class="modal-content">
            <div class="row" style="padding: 10px">
                <label class="col-md-2 control-label">Từ ngày</label>
                <div class="col-md-4">
                    <div class="input-group">
                        <input type="text" class="form-control" value="<?=date("Y-m-d", strtotime("first day of this month"))?>" id="fdate" data-date-format="yyyy-mm-dd" data-date-viewmode="months">
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                </div>
                <label class="col-md-2 control-label">Đến ngày</label>
                <div class="col-md-4">
                    <div class="input-group">
                        <input type="text" class="form-control" value="<?=date("Y-m-d")?>" id="tdate" data-date-format="yyyy-mm-dd" >
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                </div>
                <div class="col-md-12" style="padding: 10px">
                    <button id="btnSubmit" class="btn btn-success">Xem báo cáo</button>
                </div>
            </div>


        </div>
    </div>
</div>

<script type="text/javascript" src="/joli/js/plugins/morris/raphael-min.js"></script>
<script type="text/javascript" src="/joli/js/plugins/morris/morris.min.js"></script>
<script type="text/javascript" src="/joli/js/plugins/bootstrap/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="/joli/js/plugins/datatables/jquery.dataTables.min.js"></script>

<style>
    #panelButton a{margin-bottom: 5px}
    #panelButton .btn{padding: 5px 10px; line-height:10px}
</style>

<script>
    $("#tdate,#fdate").datepicker();
    month = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
    
    $( document ).ready(function() {
        $('#btnModal').click(function(){
            $('#modalDate').modal('show')
        })
        $('#btnSubmit').click(function(){
            var url='<?=$this->url('admin-dashboard')?>?fd='+$('#fdate').val()+'&td='+$('#tdate').val();
            location.href=url;
        })

        $('#tbl3, #tbl2, #tbl1').DataTable({
            paging: true,
            ordering: false,
            info: false,
            language: {
                searchPlaceholder: "Tìm kiếm tên, điện thoại, địa chỉ"
            }
        });

    });
    
    var morrisCharts = function() {
        Morris.Donut({
            element: 'morris-donut-cat',
            data: [
                <?php
                foreach ($this->arrRevenueByProductCat as $k=>$v){
                    echo '{label: "'.$v['name'].'", value: '.$v['revenue'].'},';
                }
                ?>
            ],
            colors: ['#95B75D', '#1caf9a', '#FEA223']
        });
    }();
</script>