<?php

use Sulde\Service\Common\Common;

$title="Admin dashboard";
$this->headTitle($title);
?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li class="active">Admin dashboard</li>
</ul>
<!-- END BREADCRUMB -->

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12" id="panelButton">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="<?=$this->url('product-admin')?>" class="btn btn-default">
                        <i class="fa fa-barcode" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Sản phẩm</p>
                    </a>
                    <a href="<?=$this->url('product-user',['action'=>'export-price'])?>" class="btn btn-default">
                        <i class="fa fa-print" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">In báo giá</p>
                    </a>
                    <a href="<?=$this->url('sell-admin')?>" class="btn btn-default">
                        <i class="fa fa-tags" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Đơn hàng</p>
                    </a>
                    <a href="<?=$this->url('grocery-admin')?>" class="btn btn-default">
                        <i class="fa fa-shopping-cart" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Tạo đơn bán</p>
                    </a>

                    <a href="<?=$this->url('werehouse-admin',['action'=>'choice-supplier'])?>" class="btn btn-default">
                        <i class="fa fa-book" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Nhập kho</p>
                    </a>

                    <a href="<?=$this->url('grocery-admin',['action'=>'list'])?>" class="btn btn-default">
                        <i class="fa fa-users" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Khách hàng</p>
                    </a>

                    <a href="<?=$this->url('grocery-admin',['action'=>'cat-list'])?>" class="btn btn-default">
                        <i class="fa fa-random" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Tuyến</p>
                    </a>

                    <a href="<?=$this->url('report-admin')?>" class="btn btn-default">
                        <i class="fa fa-bar-chart-o" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Report</p>
                    </a>

                    <a href="<?=$this->url('sell-staff',['action'=>'select-delivery-car'])?>" class="btn btn-default">
                        <i class="fa fa-truck" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Đơn đang giao</p>
                    </a>

                    <a href="<?=$this->url('sell-staff',['action'=>'delivered'])?>" class="btn btn-default">
                        <i class="fa fa-trophy" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Đơn đã giao</p>
                    </a>

                    <a href="<?=$this->url('product-admin',['action'=>'recommend'])?>" class="btn btn-default">
                        <i class="glyphicon glyphicon-bullhorn" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Sản phẩm gợi ý trên APP</p>
                    </a>

                    <a href="<?=$this->url('product-admin',['action'=>'sortable'])?>" class="btn btn-default">
                        <i class="fa fa-sort" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Sort bảng giá</p>
                    </a>

                    <a href="<?=$this->url('product-user',['action'=>'export-price-sort'])?>" class="btn btn-default">
                        <i class="fa fa-sort-amount-asc" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Sort sản phẩm</p>
                    </a>

                    <a href="<?=$this->url('sell-admin',['action'=>'delivery-route'])?>" class="btn btn-default">
                        <i class="fa fa-code-fork" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Phân tuyến giao hàng</p>
                    </a>

                    <a href="<?=$this->url('sell-admin',['action'=>'delivered-route']).'?date='.(new \DateTime())->format('Y-m-d')?>" class="btn btn-default">
                        <i class="glyphicon glyphicon-send" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Bản đồ đã giao</p>
                    </a>

                    <a href="<?=$this->url('grocery-admin',['action'=>'map-location'])?>" class="btn btn-default">
                        <i class="glyphicon glyphicon-map-marker" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Cửa hàng gần nhất</p>
                    </a>

                    <a href="<?=$this->url('sell-check-admin')?>" class="btn btn-default">
                        <i class="fa fa-check-circle" style="font-size: 25pt; padding-top: 5px"></i>
                        <p style="padding-top: 5px; margin-bottom: 5px; font-weight: bold">Kiểm đơn</p>
                    </a>

                </div>
            </div>
        </div>
    </div>

    <div class="page-title" style="padding-bottom: 20px;">
        <span id="btnModal" style="width: 30px" class="input-group-addon add-on">
            <span class="glyphicon glyphicon-calendar"></span> <?=$this->strReportDate?>
        </span>
    </div>
    <div class="row">
        <div class="col-md-3">
            <!-- START TABS -->
            <div class="panel panel-default">
                <div class="panel-heading panel-title">Doanh thu</div>
                <div class="panel-body">
                    <div style="text-align: center"><span class="fa fa-signal" style="font-size: 100pt; color: #2db3dc"></span></div>
                    <h4>DOANH THU</h4>
                    <div style="color: #2db3dc; font-size: 18pt; font-weight: bold"><?=Common::formatMoney($this->totalRevenue)?></div>
                    <div><b>Tổng đơn hàng: <?=$this->orderNumber?></b></div>
                    <div style="text-align: left; padding-top: 30px"><b>Doanh thu:</b> Bằng tổng giá trị các đơn hàng giao thành công đã trừ trả hàng.</div>

                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading panel-title">Sản phẩm</div>
                <div class="panel-body">
                    <div id="morris-donut-cat" style="height: 300px; width:300px"></div>
                </div>
            </div>
            <!-- END TABS -->
        </div>
        <div class="col-md-9">
            <div class="panel panel-default">
                <div class="panel-heading panel-title">
                    Khách hàng cần chú ý hôm nay (Số liệu 12 tháng gần nhất)
                </div>

                <div class="panel-body">
                    <table class="table nowrap table-hover display" style="width:100%" id="tblRiskCustomers">
                        <thead>
                        <tr>
                            <th>visible</th>
                            <th>STT</th>
                            <th>Khách hàng</th>
                            <th>Số ngày chưa lên đơn</th>
                            <th>Chu kỳ lên đơn (ngày)</th>
                            <th>Đã quá chu kỳ nhập (ngày)</th>
                            <th>Độ tin cậy chu kỳ nhập</th>
                            <th>Doanh thu</th>
                            <th>Risk</th>
                        </tr>
                        </thead>
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade bottom" id="modalDate" tabindex="-1" role="dialog" aria-labelledby="modalDate" aria-hidden="true">
    <input id="local" value="" type="hidden">
    <div class="modal-dialog modal-bottom" role="document">
        <div class="modal-content">
            <div class="row" style="padding: 10px">
                <label class="col-md-2 control-label">Từ ngày</label>
                <div class="col-md-4">
                    <div class="input-group">
                        <input type="text" class="form-control" value="<?=date("Y-m-d", strtotime("first day of this month"))?>" id="fdate" data-date-format="yyyy-mm-dd" data-date-viewmode="months">
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                </div>
                <label class="col-md-2 control-label">Đến ngày</label>
                <div class="col-md-4">
                    <div class="input-group">
                        <input type="text" class="form-control" value="<?=date("Y-m-d")?>" id="tdate" data-date-format="yyyy-mm-dd" >
                        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                </div>
                <div class="col-md-12" style="padding: 10px">
                    <button id="btnSubmit" class="btn btn-success">Xem báo cáo</button>
                </div>
            </div>


        </div>
    </div>
</div>

<script type="text/javascript" src="/joli/js/plugins/morris/raphael-min.js"></script>
<script type="text/javascript" src="/joli/js/plugins/morris/morris.min.js"></script>
<script type="text/javascript" src="/joli/js/plugins/bootstrap/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="/joli/js/plugins/datatables/jquery.dataTables.min.js"></script>

<script type="text/javascript" src="/joli/js/plugins/datatables/jquery.dataTables.2.1.8.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/dataTables.dataTables.css"/>

<style>
    #panelButton a{margin-bottom: 5px}
    #panelButton .btn{padding: 5px 10px; line-height:10px}
    .panel-body table tr td{
        vertical-align: middle;
    }
    .dt-length label{
        display: none;
    }
    .dt-length select{
        width: 50px;
        display: inline-block;
    }
</style>

<script>
    $("#tdate,#fdate").datepicker();
    month = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
    
    $( document ).ready(function() {

        let tblRiskCustomers =$('#tblRiskCustomers').DataTable({
            info:false,
            paging: false,
            pageLength:20,
            ordering: false,
            processing: false,
            serverSide: false,
            stateSave: false,
            autoWidth: false,
            language: {
                searchPlaceholder: ""
            },
            search: {
                return: true
            },
            columnDefs: [
                { name:'id', targets: 0, visible: false},
                { name:'stt', targets: 1, orderable: false},
                { name:'groceryName', targets: 2, className: 'title',
                    createdCell:function (td, cellData, rowData, row, col){
                    //console.log(rowData);
                        let url='<?=$this->url('grocery-admin',['action'=>'detail', 'id' => '__id__'])?>';
                        let name = '<a class="title" href="' + url.replace('__id__', rowData[0].customer_id) + '">' + cellData + '</a>';
                        $(td).html(name);
                    }
                },
                {
                    name: 'stability', targets: 6,
                    createdCell: function (td, cellData, rowData, row, col) {
                        if (cellData >= 85) {
                            $(td).html('<span class="label label-success">Rất ổn định ('+cellData+'%)</span>');
                        } else if (cellData >= 70 && cellData < 85) {
                            $(td).html('<span class="label label-info">Ổn định định ('+cellData+'%)</span>');
                        } else if (cellData >= 50 && cellData < 70) {
                            $(td).html('<span class="label label-warning">Trung bình ('+cellData+'%)</span>');
                        } else {
                            $(td).html('<span class="label label-danger">Thất thường ('+cellData+'%)</span>');
                        }
                    }
                }
            ],
            ajax: {
                url: '<?=$this->url('grocery-admin',['action'=>'top-risk-customers'])?>',
                type: 'POST',
                dataSrc: function (json) {
                    let data=[];
                    let i=1;
                    $.each( json.customers, function( key, value ) {
                        let dataItem=[];
                        dataItem.push(value);
                        dataItem.push(i++);
                        dataItem.push(value.customer_name);
                        dataItem.push(value.last_order_days);
                        dataItem.push(value.avg_cycle_days);
                        dataItem.push(value.overdue_days);
                        dataItem.push(value.stability);
                        dataItem.push(formatPrice(value.revenue));
                        dataItem.push(value.risk);
                        data.push(dataItem);
                    });

                    return data;
                }
            }
        }).on('click', 'tbody tr', (e) => {
            let classList = e.currentTarget.classList;

            if (classList.contains('tr-selected')) {
                classList.remove('tr-selected');
            }
            else {
                tblRiskCustomers.rows('.tr-selected').nodes().each((row) => row.classList.remove('tr-selected'));
                classList.add('tr-selected');
            }
        });


        $('#btnModal').click(function(){
            $('#modalDate').modal('show')
        })
        $('#btnSubmit').click(function(){
            var url='<?=$this->url('admin-dashboard')?>?fd='+$('#fdate').val()+'&td='+$('#tdate').val();
            location.href=url;
        })

    });
    
    let morrisCharts = function() {
        Morris.Donut({
            element: 'morris-donut-cat',
            data: [
                <?php
                foreach ($this->arrRevenueByProductCat as $k=>$v){
                    echo '{label: "'.$v['name'].'", value: '.$v['revenue'].'},';
                }
                ?>
            ],
            colors: ['#95B75D', '#1caf9a', '#FEA223']
        });
    }();
</script>