<?php

use Sulde\Service\Common\Common;
use Sulde\Service\Common\ConfigManager;

$title = "";
$this->headTitle($title);


?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('admin-dashboard')?>">Home</a></li>
    <li class="active"><?=$title?></li>
</ul>
<!-- END BREADCRUMB -->

<div class="page-title">
    <h2><span class="fa fa-arrow-circle-o-left"></span> Cửa hàng: <?=$this->groceryDetail->getGroceryName()?></h2>
</div>

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <?php
            if(count($this->flashMessenger()->getSuccessMessages())>0){
                ?>
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->getSuccessMessages()[0]?>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form id="jvalidate" role="form" class="form-horizontal" method="post" action="<?=$this->url('grocery-admin',['action'=>'crm','id'=>$this->groceryDetail->getId()])?>">
                        <div class="form-group">
                            <label class="col-md-2 control-label">Ghi chú:</label>
                            <div class="col-md-8">
                                <textarea class="form-control" name="note" id="note" rows="5"></textarea>
                                <span class="help-block">Vui lòng nhập ghi chú!</span>
                            </div>
                        </div>
                        <label class="col-md-2 control-label"></label>
                        <div class="col-md-8">
                            <button class="btn btn-info" type="submit">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<style>
.grocery-info div{padding-bottom: 5px; padding-top: 5px; border-bottom: 1px solid #E5E5E5}
.grocery-info div:last-child{border-bottom: 0px}
</style>
<script type='text/javascript' src='/joli/js/plugins/jquery-validation/jquery.validate.js'></script>
<script type="text/javascript">
    var jvalidate = $("#jvalidate").validate({
        ignore: [],
        rules: {
            note: {
                required: true
            }
        }
    });

</script>