<?php

use Sulde\Service\Common\Common;

$title = "Danh sách cửa hàng";
$this->headTitle($title);


?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('admin-dashboard')?>">Home</a></li>
    <li class="active"><?=$title?></li>
</ul>
<!-- END BREADCRUMB -->

<div class="page-title">
    <h3>
        <span class="fa fa-arrow-circle-o-left"></span> Danh sách khách hàng        
    </h3>
</div>

<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <?php
            if(count($this->flashMessenger()->getSuccessMessages())>0){
                ?>
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->getSuccessMessages()[0]?>
                </div>
                <?php
            }
            ?>
        </div>
    </div>
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-body">
                <table id="tblGrocery" class="display" style="width:100%">
                    <thead>
                    <tr>
                        <th></th>
                        <th>No.</th>
                        <th>Tên cửa hàng</th>
                        <th>Chủ cửa hàng</th>
                        <th>Mobile</th>
                        <th>Nhân viên</th>
                        <th>check in date</th>
                    </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="/joli/js/plugins/datatables/jquery.dataTables.2.1.8.min.js"></script>
<link rel="stylesheet" type="text/css" href="/css/dataTables.dataTables.css"/>

<link rel="stylesheet" href="/css/responsive.dataTables.min.css">
    <script src="/joli/js/plugins/datatables/dataTables.responsive.min.js"></script>
<style>
    #tblGrocery a{color: #0d0d0d}
    #tblGrocery .title{font-weight: bold; font-size: 14px; color: #067fad
    }
    #tblGrocery p{margin-bottom: 5px}
    #tblGrocery td{padding-bottom: 5px; padding-top: 5px}
    #tblGrocery td:first-child{padding-right: 5px; padding-bottom: 5px; padding-top: 10px}
    #tblGrocery tr{border-bottom: 1px solid #E5E5E5}    
    .dt-layout-row select{width: 50px; display: none}
    .dt-layout-row label{display: none}
</style>

<script>
    $(document).ready(function () {
        let tblGrocery=$('#tblGrocery').DataTable({
            responsive:true,
            info:false,
            paging: true,
            pageLength:<?=\Sulde\Service\Common\Define::ITEM_PAGE_COUNT?>,
            ordering: false,
            processing: true,
            serverSide: true,
            stateSave: false,
            autoWidth: false,
            layout: {
                topStart: null,  // ❌ tắt ô search mặc định
                topEnd: null,    // ❌ tắt length dropdown mặc định
                top: ['search', 'pageLength']
            },
            language: {
                searchPlaceholder: "Tìm kiếm theo tên, điện thoại, địa chỉ, nhân viên."
            },
            columnDefs: [
                { name:'data', targets: 0, visible: false},
                { targets: [1],width: '20px'},
                { targets: [4,5],width: '100px',className: 'min-desktop'},
                { targets: [3,6],width: '120px',className: 'min-desktop'},
                { name: 'name', targets: 2, className:'dt-body-left',
                   createdCell:function (td, cellData, rowData, row, col){
                        let url='<?=$this->url('grocery-admin',['action'=>'detail', 'id' => '__id__'])?>';
                        let name = '<a class="title" href="' + url.replace('__id__', rowData[0].id) + '">' + cellData + '</a>';
                        let address = '<p><i>' + rowData[0].address + '</i></p>';
                        let title = name + address;
                        $(td).html(title);
                    }                    
                }
            ],
            ajax: {
                url: '<?=$this->url('grocery-admin', ['action'=>'list'])?>',
                type: 'POST',
                dataSrc: function (json) {
                    let data=[];
                    let i=parseInt(json.start)+1;                    
                    $.each( json.data, function( key, value ) {
                        let dataItem=[];
                        dataItem.push(value);
                        dataItem.push(i++);
                        dataItem.push(value.name);
                        dataItem.push(value.owner_name);
                        dataItem.push(value.mobile);
                        dataItem.push(value.staff_in_charge);
                        dataItem.push(value.check_in_date);
                        data.push(dataItem);
                    });
                    return data;
                }
            },
            initComplete: function () {
                $(this.api().table().container()).find('input[type="search"]').attr('autocomplete', 'off');
            }
        }).on('click', 'tbody tr', (e) => {
            let classList = e.currentTarget.classList;

            if (classList.contains('tr-selected')) {
                classList.remove('tr-selected');
            }
            else {
                tblGrocery.rows('.tr-selected').nodes().each((row) => row.classList.remove('tr-selected'));
                classList.add('tr-selected');
            }
        });
    });
</script>