<?php

use Sulde\Service\Common\Common;

?>
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('admin-dashboard')?>">Home</a></li>
    <li><a href="<?=$this->url('sell-admin')?>">Danh sách đơn hàng</a></li>
    <li class="active">Chi tiết đơn hàng</li>
</ul>
<div class="page-title">
    <h3><span class="fa fa-arrow-circle-o-left"></span> Chi tiết đơn hàng <?=$this->sellOrder->getSupplier()->getName()?> <?=$this->sellOrder->getOrderCode()?></h3>
</div>
<div class="page-content-wrap">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-body">
                <ul id="productList" class="list-group">
                    <?php
                    foreach ($this->sellOrder->getSell() as $sell){
                    ?>
                    <li href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1 title"><?=$sell->getProduct()->getCode()?> | <?=$sell->getProduct()->getName()?> | <?=$sell->getProduct()->getWeight()?></h5>
                        </div>
                        <table style="width: 100%">
                            <tbody>
                            <tr>
                                <td style="padding-right: 5px; width: 40px">
                                    <img src="<?=$sell->getProduct()->getImg()?>" style="max-width:40px; max-height:30px">
                                </td>
                                <td>
                                    <table style=" width: 100%;" >
                                        <tbody>
                                        <tr>
                                            <td style="padding-left: 10px;" nowrap="">Giá bán:</td>
                                            <td style="padding-left: 10px; padding-right: 10px" nowrap="">Số lượng:</td>
                                            <td style="padding-left: 5px">Thành tiền:</td>
                                        </tr>
                                        <tr>
                                            <td style="padding-left: 10px; font-weight: bold;" nowrap=""><?=Common::formatMoney($sell->getPrice()->getPrice())?> đ
                                            </td>
                                            <td style="padding-left: 10px;"><?=$sell->getQuantity().' '.$sell->getProduct()->getUnit()->getName()?> <small class="warning-color"><?=($sell->getReturn()>0?' (Trả lại: '.$sell->getReturn().')':'')?></small></td>
                                            <?php
                                            $totalMoney=$sell->getQuantity()*$sell->getPrice()->getPrice();
                                            $profit = $totalMoney - $sell->getQuantity()*$sell->getProduct()->getAveragePrice();
                                            ?>
                                            <td style="padding-left: 5px"><?=Common::formatMoney($totalMoney)?> đ <small style="color: #0C7FCC">(<?=Common::formatMoney($profit)?>)</small></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <small id="msg15" class="warning-color"></small>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </li>
                    <?php
                    }
                    ?>
                    <li href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-between">
                            <h5 class="mb-1 title" style="color: #26a9d1; text-align: right">Tổng đơn: <?=Common::formatMoney($this->sellOrder->getTotalPrice())?> đ</h5>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<style>
    .list-group-item .title{font-weight: bold}
    .list-group .list-group-item:last-child{
        border-bottom: 1px solid #E5E5E5;
    }
    .price{color: #26a9d1; font-weight: bold; padding-left: 10px}
    .warning-color{color: red}
</style>