<?php

use Sulde\Service\Common\Common;

$this->headTitle("Kiểm kho");
?>
<style>.error{color: red}</style>
<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('grocery-user')?>">Home</a></li>
    <li class="active">Danh sách phiếu kiểm kho</li>
</ul>
<!-- END BREADCRUMB -->

<div class="page-title">
    <h3><span class="fa fa-arrow-circle-o-left"></span> Danh sách phiếu kiểm kho</h3>
</div>
<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <?php
            if(count($this->flashMessenger()->getErrorMessages())>0){
                ?>
                <div class="alert alert-danger" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <?=$this->flashMessenger()->getErrorMessages()[0]?>
                </div>
                <?php
            }
            ?>
        </div>
        <div class="col-md-8">
            <div class="panel panel-default">
                <div class="panel-heading ui-draggable-handle">
                    <h3 class="panel-title"></h3>
                    <button onclick="showModalInventorySheet()" class="btn btn-info"><span class="fa fa-plus"></span>Tạo phiếu kiểm kho</button>
                </div>
                <div class="panel-body">
                    <table class="table table-hover display" id="tblSheet">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>Người kiểm</th>
                            <th>Ngày kiểm</th>
                            <th>Sản phẩm kiểm</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php
                        foreach ($this->werehouseSheet as $werehouseSheetItem){
                        ?>
                        <tr>
                            <td><?=$werehouseSheetItem->getId()?></td>
                            <td>
                                <a href="<?=$this->url('werehouse-admin',['action'=>'inventory-check','id'=>$werehouseSheetItem->getId()])?>"><?=$werehouseSheetItem->getUser()->getFullname()?></a>
                            </td>
                            <td><?=Common::formatDateTime($werehouseSheetItem->getCreatedDate())?></td>
                            <td><?=count($werehouseSheetItem->getWerehouseCheck())?></td>
                        </tr>
                        <?php
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalSelectProduct" tabindex="-1" role="dialog" aria-labelledby="modalSelectProductLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <form method="post" action="<?=$this->url('werehouse-admin',['action'=>'inventory-sheet'])?>" enctype="multipart/form-data">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="modalSelectProductLabel">Thông tin phiếu kiểm kho</h4>
            </div>
            <div class="modal-body">

                <table class="table table-hover display">
                    <tbody>
                    <tr>
                        <td>Người kiểm:</td>
                        <td><b><?=$this->userInfo->getFullname()?></b></td>
                    </tr>
                    <tr>
                        <td>Ngày kiểm:</td>
                        <td><b><?=Common::formatDateTime(new DateTime())?></b></td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Huỷ</button>
                <button type="submit" class="btn btn-success">Tạo phiếu kiểm kho</button>
            </div>
            </form>
        </div>
    </div>
</div>
<script type="text/javascript" src="/joli/js/plugins/datatables/jquery.dataTables.min.js"></script>
<script>
    $( document ).ready(function() {
        $('#tblSheet').DataTable({
            paging: true,
            pageLength:10,
            ordering: true,
            info: false,
            searching:true,
            order: [[ 0, "DESC" ]]
        });
    })

    function showModalInventorySheet(){
        // $('#btnAddProductToOrder').prop('disabled', true);
        $('#modalSelectProduct').modal({
            keyboard: false,
            backdrop:'static',
            show:true
        });
    }
</script>