<?php

function cc($amount,$GeoIp) {

    if ( isset($GeoIp->geoplugin_currencyCode) && $GeoIp->geoplugin_currencyCode != 'USD' ) {
        return '(' . $GeoIp->geoplugin_currencySymbol . round( ($amount * $GeoIp->geoplugin_currencyConverter),2) . ')';
    }
    return false;
}
?>
<div class="jumbotron">
    <h1>zf3-geolocation</span></h1>

    <p>
        <?php echo $Weather?>
    </p>
    <p>
        <?php echo 'Welcome to our visitors from: '.$GeoIp->geoplugin_countryName;?>
    </p>
    ccc <?=$this->GeoIp->geoplugin_longitude ?>
    <p>
        <?php  echo "Geolocation results for : <br />\n".
            "City: {$GeoIp->geoplugin_city} <br />\n".
            "Region: {$GeoIp->geoplugin_region} <br />\n".
            "Area Code: {$GeoIp->geoplugin_areaCode} <br />\n".
            "DMA Code: {$GeoIp->geoplugin_dmaCode} <br />\n".
            "Country Name: {$GeoIp->geoplugin_countryName} <br />\n".
            "Country Code: {$GeoIp->geoplugin_countryCode} <br />\n".
            "Longitude: {$GeoIp->geoplugin_longitude} <br />\n".
            "Latitude: {$GeoIp->geoplugin_latitude} <br />\n".
            "Currency Code: {$GeoIp->geoplugin_currencyCode} <br />\n".
            "Currency Symbol: {$GeoIp->geoplugin_currencySymbol} <br />\n".
            "Exchange Rate: {$GeoIp->geoplugin_currencyConverter} <br />\n";
        ?></p>
    <p><?php  echo '<h3>Product A costs $800  ' . cc(800,$GeoIp) . '</h3>'; ?></p>
</div>