<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default" style="font-size: 14pt; font-family: Arial">
            <div class="panel-body">
                <div class="col-md-12">
                    <h3>NPP Anh Vũ Kính chào Quý Khách,</h3>
                    <p><i>Nhằm hướng tới mục tiêu đã đề ra, Chúng tôi luôn luôn lắng nghe, liên tục thay đổi và cải tiến để đem đến cho khách hàng những trải nghiệm cũng như tiện lợi nhất. Ứng dụng đặt hàng đã có mặt trên nền tảng zalo, giúp bạn tương tác, tìm kiếm sản phẩm cũng như đặt hàng và quản lý đơn hàng một cách hiệu quả và thuận tiện. Chỉ cần điện thoại của bạn có sẵn Zalo bạn có thể truy cập ứng dụng bất kỳ lúc nào bạn muốn. Vui lòng làm theo hướng dẫn bên dưới để cài đặt ựng dụng. <a href="<?=$this->url('product-front')?>">tiếp tục đặt hàng trên web</a></i></p>
                </div>
                <div class="col-md-12" style="padding-top: 15px">
                    <h3>HƯỚNG DẪN CÀI ĐẶT VÀ ĐẶT HÀNG TRÊN ỨNG DỤNG</h3>
                </div>
                <div class="col-md-4">
                    <p style="font-weight: bold">A: Cài đặt bằng cách quét mã QR</p>
                    <p><i>Nếu bạn có mã QR cài đặt ứng dụng, vui lòng mở zalo và làm theo hướng dẫn</i></p>
                    <p><img src="/img/zalo/cai-quet-qr.gif" style="width: 90%"></p>
                </div>
                <div class="col-md-4">
                    <p style="font-weight: bold">B: Cài đặt bằng cách tìm tên trên zalo</p>
                    <p><i>Vui lòng mở zalo và làm theo hướng dẫn</i></p>
                    <p><img src="/img/zalo/cai-tim-ten.gif" style="width: 90%"></p>
                </div>
                <div class="col-md-4">
                    <p style="font-weight: bold">C: Đặt hàng</p>
                    <p><i>Vui lòng mở ứng dụng NPP Anh Vũ và làm theo hướng dẫn</i></p>
                    <p><img src="/img/zalo/dat-hang.gif" style="width: 90%"></p>
                </div>
            </div>
        </div>
    </div>
</div>
