<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default" style="font-size: 14pt; font-family: Arial">
            <div class="panel-body">
                <div class="col-md-12">
                    <h3>NPP Anh Vũ Kính chào Quý Khách,</h3>
                    <p>Chúng tôi luôn nỗ lực cải tiến mỗi ngày để mang đến cho khách hàng trải nghiệm mua hàng nhanh chóng, thuận tiện và hiệu quả nhất.</p>
                    <p>Để giúp việc đặt hàng trở nên dễ dàng hơn, ứng dụng đặt hàng của chúng tôi đã được tích hợp trực tiếp trên Zalo. Bạn có thể tìm kiếm sản phẩm, đặt hàng, theo dõi lịch sử mua hàng và quản lý đơn hàng chỉ với vài thao tác đơn giản.</p>
                    <p>Không cần cài đặt thêm ứng dụng mới, chỉ cần sử dụng Zalo trên điện thoại là bạn có thể truy cập và đặt hàng bất cứ lúc nào.</p>
                    <p><a href="https://zalo.me/s/107575948294337759/" target="_blank"><b>Nhấp vào đây để mở ứng dụng đặt hàng trên Zalo!</b></a> hoặc làm theo hướng dẫn bên dưới để mở ứng dụng đặt hàng trên Zalo!</p>                    
                </div>
                <div class="col-md-12" style="padding-top: 15px">
                    <h3>HƯỚNG DẪN CÀI ĐẶT VÀ ĐẶT HÀNG TRÊN ỨNG DỤNG</h3>
                </div>
                <div class="col-md-4">
                    <p style="font-weight: bold">A: Cài đặt bằng cách quét mã QR</p>
                    <p><i>Nếu bạn có mã QR cài đặt ứng dụng, vui lòng mở zalo và làm theo hướng dẫn</i></p>
                    <p><img src="/img/zalo/cai-quet-qr.gif" style="width: 90%"></p>
                </div>
                <div class="col-md-4">
                    <p style="font-weight: bold">B: Cài đặt bằng cách tìm tên trên zalo</p>
                    <p><i>Vui lòng mở zalo và làm theo hướng dẫn</i></p>
                    <p><img src="/img/zalo/cai-tim-ten.gif" style="width: 90%"></p>
                </div>
                <div class="col-md-4">
                    <p style="font-weight: bold">C: Đặt hàng</p>
                    <p><i>Vui lòng mở ứng dụng NPP Anh Vũ và làm theo hướng dẫn</i></p>
                    <p><img src="/img/zalo/dat-hang.gif" style="width: 90%"></p>
                </div>
            </div>
        </div>
    </div>
</div>
