<?php
$title = "Truonghm admin";
$this->headTitle($title);


?>

<!-- START BREADCRUMB -->
<ul class="breadcrumb">
    <li><a href="<?=$this->url('admin-dashboard')?>">Home</a></li>
    <li class="active">TruongHM list</li>
</ul>
<!-- END BREADCRUMB -->



<!-- PAGE CONTENT WRAPPER -->
<div class="page-content-wrap">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                	This content
                </div>
            </div>
        </div>
    </div>
</div>