<?php
use Sulde\Service\Common\Common;
use Sulde\Service\Common\ConfigManager;

?>
<?= $this->doctype() ?>

<html lang="vi" class="h-100">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Anh Vũ - Thế giới hàng tiêu dùng')->setSeparator(' - ')->setAutoEscape(false) ?>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1,user-scalable=no,viewport-fit=cover">
    <?= $this->headMeta()
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <meta name="robots" content="index,follow">
    <meta name="author" content="Anhvu">
    <meta name="description" content="">
    <meta name="apple-mobile-web-app-title" content="anhvu.store">
    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/favicon.png'])?>

    <!-- CSS INCLUDE -->
    <!-- CSS INCLUDE -->
    <link rel="stylesheet" type="text/css" id="theme" href="/joli/css/theme-default.css"/>

    <!-- START SCRIPTS -->
    <!-- START PLUGINS -->
    <script type="text/javascript" src="/joli/js/plugins/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/joli/js/plugins/jquery/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/joli/js/plugins/bootstrap/bootstrap.min.js"></script>
    <!-- END PLUGINS -->

    <!-- START NOTY -->
    <script type='text/javascript' src='/joli/js/plugins/noty/jquery.noty.js'></script>
    <script type='text/javascript' src='/joli/js/plugins/noty/layouts/topRight.js'></script>
    <script type='text/javascript' src='/joli/js/plugins/noty/themes/default.js'></script>

    <!-- THIS PAGE PLUGINS -->
    <script type="text/javascript" src="/joli/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js"></script>
    <!-- END PAGE PLUGINS -->

    <!-- START TEMPLATE -->
    <script type="text/javascript" src="/joli/js/plugins.js"></script>
    <script type="text/javascript" src="/joli/js/actions.js"></script>

    <link href="/vendor/jquery/waitMe/waitMe.css" rel="stylesheet">
    <script src="/vendor/jquery/waitMe/waitMe.js"></script>
    <script type="text/javascript" src="/js/admin.js"></script>
</head>
<body class="d-flex flex-column h-100">

<!-- Begin page content -->
<main role="main">
    <div class="row">
        <div class="col-md-12">
            <div style="background-color: #ff6700; width: 40%;  padding: 5px" class="pull-left">
                <a href="/" style="padding-top: 2px"><img src="/img/logo-user-admin.png" width="120px"></a>
            </div>
            <div style="background-color: #000000; width: 60%; height: 57px; text-align: right; border: 1px solid red" class="pull-right">
                <div class="pull-right">
                    <a href="<?=$this->url('product-front',['action'=>'my-cart'])?>">
                        <i class="fa fa-shopping-cart" style="color: white; font-size: 13pt; margin-top: 20px; margin-right: 10px">
                            <div style="right: 36px; top: 10px; position: absolute; background-color: #1caf9a; padding: 2px; font-size: 14px; -webkit-border-radius:3px" id="c_my_card">
                                <?php
                                if(isset($_SESSION['cart'])){
                                  echo @count($_SESSION['my_card']);
                                }
                                ?>
                            </div>
                        </i>
                    </a>
                </div>
                <?php
                if($this->authIdentity){
                    ?>
                <div class="pull-right" style="padding-right: 20px">
                    <a href="<?=$this->url('user-dashboard')?>">
                        <i class="fa fa-user" style="color: white; font-size: 13pt; margin-top: 20px; margin-right: 10px"> <?=$this->authIdentity->getFullname()?></i>
                    </a>
                </div>
                <?php
                }
                ?>
            </div>

        </div>
    </div>
</main>

<div class="page-content">
    <div class="page-content-wrap">
    <?= $this->content ?>
    </div>
</div>
<style>
    .x-navigation > li.xn-logo > a:first-child{background-color: #ff6700}
</style>
</body>
</html>